"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    // Insert GRNs
    const grns = await queryInterface.bulkInsert(
      "grns",
      [
        {
          grn_no: "GRN 01/24-25",
          grn_date: "2025-05-19",
          grn_info_ids: [1, 2, 3, 4, 5, 6, 7, 8], // NEW FIELD
          po_id: 1,
          vendor_id: 1,
          order_by_user_id: 2,
          reference_id: "10023",
          gst_no: "33AADFT0604Q1Z6",
          billing_address: "18, Vaniet Street George Town, Chennai, Tamil Nadu - 600001",
          shipping_address: "18, Vaniet Street George Town, Chennai, Tamil Nadu - 600001",
          subtotal_amount: 24000.0,
          sgst_percent: 0.0,
          cgst_percent: 2.0,
          discount_percent: 2.0,
          remarks: "Initial test GRN entry.",
          status_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
        },
        {
          grn_no: "GRN 02/24-25",
          grn_date: "2025-05-20",
          grn_info_ids: [9, 10, 11, 12, 13, 14, 15, 16, 17], // NEW FIELD
          po_id: 2,
          vendor_id: 2,
          order_by_user_id: 3,
          reference_id: "10024",
          gst_no: "33AAABT0707L1Z9",
          billing_address: "10, Mint Street, Chennai, Tamil Nadu - 600001",
          shipping_address: "10, Mint Street, Chennai, Tamil Nadu - 600001",
          subtotal_amount: 18000.0,
          sgst_percent: 2.5,
          cgst_percent: 2.5,
          discount_percent: 1.0,
          remarks: "Silver item GRN.",
          status_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
        },
        {
          grn_no: "GRN 03/24-25",
          grn_date: "2025-05-21",
          grn_info_ids: [18, 19, 20, 21, 22, 23, 24, 25, 26, 17], // NEW FIELD
          po_id: 3,
          vendor_id: 1,
          order_by_user_id: 4,
          reference_id: "10025",
          gst_no: "33AACCT0505Q1Z1",
          billing_address: "1, Mount Road, Chennai, Tamil Nadu - 600002",
          shipping_address: "1, Mount Road, Chennai, Tamil Nadu - 600002",
          subtotal_amount: 50000.0,
          sgst_percent: 2.0,
          cgst_percent: 2.0,
          discount_percent: 0.0,
          remarks: "Bulk gold jewelry GRN.",
          status_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
        },
        {
          grn_no: "GRN 04/24-25",
          grn_date: "2025-05-22",
          grn_info_ids: null, // no data (allowed)
          po_id: 4,
          vendor_id: 3,
          order_by_user_id: 5,
          reference_id: "10026",
          gst_no: "33AAACT0303Q1Z3",
          billing_address: "5, Broadway, Chennai, Tamil Nadu - 600108",
          shipping_address: "5, Broadway, Chennai, Tamil Nadu - 600108",
          subtotal_amount: 12000.0,
          sgst_percent: 1.0,
          cgst_percent: 1.0,
          discount_percent: 0.5,
          remarks: "Miscellaneous GRN for testing.",
          status_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
        },
      ],
      { returning: true }
    );

    // Insert GRN Items (unchanged)
    await queryInterface.bulkInsert("grnItems", [
      {
        grn_id: 1,
        material_type_id: 1,
        category_id: 1,
        subcategory_id: 1,
        description: "Flower Stud",
        purity: 92.5,
        ordered_weight: 250.0,
        received_weight: 200.0,
        quantity: 1,
        rate: 10525.0,
        amount: 152585.0,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        grn_id: 2,
        material_type_id: 2,
        category_id: 3,
        subcategory_id: 2,
        description: "Silver Ring",
        purity: 91.6,
        ordered_weight: 100.0,
        received_weight: 95.0,
        quantity: 2,
        rate: 9000.0,
        amount: 17100.0,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        grn_id: 3,
        material_type_id: 1,
        category_id: 2,
        subcategory_id: 5,
        description: "Gold Chain",
        purity: 99.9,
        ordered_weight: 50.0,
        received_weight: 50.0,
        quantity: 1,
        rate: 5800.0,
        amount: 290000.0,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        grn_id: 4,
        material_type_id: 3,
        category_id: 4,
        subcategory_id: 6,
        description: "Platinum Earrings",
        purity: 95.5,
        ordered_weight: 20.0,
        received_weight: 19.5,
        quantity: 1,
        rate: 12000.0,
        amount: 234000.0,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("grnItems", null, {});
    await queryInterface.bulkDelete("grns", null, {});
  },
};
