"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    // Insert GRNs
    const grns = await queryInterface.bulkInsert(
      "grns",
      [
        {
          grn_no: "GRN001",
          grn_date: "2025-05-19",
          grn_info_ids: [1, 2, 3, 4, 5, 6, 7, 8], // NEW FIELD
          po_id: 1,
          vendor_id: 1,
          order_by_user_id: 2,
          reference_id: "10023",
          gst_no: "33AADFT0604Q1Z6",
          billing_address:
            "18, Vaniet Street George Town, Chennai, Tamil Nadu - 600001",
          shipping_address:
            "18, Vaniet Street George Town, Chennai, Tamil Nadu - 600001",
          subtotal_amount: 24000.0,
          sgst_percent: 0.0,
          cgst_percent: 2.0,
          discount_percent: 2.0,
          remarks: "Initial test GRN entry.",
          status_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
        },
        {
          grn_no: "GRN002",
          grn_date: "2025-05-20",
          grn_info_ids: [9, 10, 11, 12, 13, 14, 15, 16, 17], // NEW FIELD
          po_id: 2,
          vendor_id: 2,
          order_by_user_id: 3,
          reference_id: "10024",
          gst_no: "33AAABT0707L1Z9",
          billing_address: "10, Mint Street, Chennai, Tamil Nadu - 600001",
          shipping_address: "10, Mint Street, Chennai, Tamil Nadu - 600001",
          subtotal_amount: 18000.0,
          sgst_percent: 2.5,
          cgst_percent: 2.5,
          discount_percent: 1.0,
          remarks: "Silver item GRN.",
          status_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
        },
        {
          grn_no: "GRN003",
          grn_date: "2025-05-21",
          grn_info_ids: [18, 19, 20, 21, 22, 23, 24, 25, 26, 17], // NEW FIELD
          po_id: 3,
          vendor_id: 1,
          order_by_user_id: 4,
          reference_id: "10025",
          gst_no: "33AACCT0505Q1Z1",
          billing_address: "1, Mount Road, Chennai, Tamil Nadu - 600002",
          shipping_address: "1, Mount Road, Chennai, Tamil Nadu - 600002",
          subtotal_amount: 50000.0,
          sgst_percent: 2.0,
          cgst_percent: 2.0,
          discount_percent: 0.0,
          remarks: "Bulk gold jewelry GRN.",
          status_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
        },
        {
          grn_no: "GRN004",
          grn_date: "2025-05-22",
          grn_info_ids: null, // no data (allowed)
          po_id: 4,
          vendor_id: 3,
          order_by_user_id: 5,
          reference_id: "10026",
          gst_no: "33AAACT0303Q1Z3",
          billing_address: "5, Broadway, Chennai, Tamil Nadu - 600108",
          shipping_address: "5, Broadway, Chennai, Tamil Nadu - 600108",
          subtotal_amount: 12000.0,
          sgst_percent: 1.0,
          cgst_percent: 1.0,
          discount_percent: 0.5,
          remarks: "Miscellaneous GRN for testing.",
          status_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
        },
      ],
      { returning: true }
    );

    await queryInterface.bulkInsert("grnItems", [
      {
        grn_id: 1,
        ref_no: "GRN001/01",
        material_type_id: 1,
        category_id: 1,
        subcategory_id: 1,
        purity: "92.5",
        type: "Piece",
        quantity: 1,
        gross_wt_in_g: 14.5,
        stone_wt_in_g: 0,
        net_wt_in_g: 14.5,
        purchase_rate: 10525.0,
        rate_per_g: 10525.0,
        total_amount: 152585.0,
        comments: "Gold ring item",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        grn_id: 2,
        ref_no: "GRN002/01",
        material_type_id: 2,
        category_id: 3,
        subcategory_id: 2,
        purity: "99.9",
        type: "Piece",
        quantity: 2,
        gross_wt_in_g: 1.9,
        stone_wt_in_g: 0,
        net_wt_in_g: 1.9,
        purchase_rate: 9000.0,
        rate_per_g: 9000.0,
        total_amount: 17100.0,
        comments: "Silver ring",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        grn_id: 3,
        ref_no: "GRN003/01",
        material_type_id: 1,
        category_id: 2,
        subcategory_id: 5,
        purity: "99.9",
        type: "Weight",
        quantity: 1,
        gross_wt_in_g: 50.0,
        stone_wt_in_g: 0,
        net_wt_in_g: 50.0,
        purchase_rate: 5800.0,
        rate_per_g: 5800.0,
        total_amount: 290000.0,
        comments: "Bulk gold jewelry",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        grn_id: 4,
        ref_no: "GRN004/01",
        material_type_id: 3,
        category_id: 4,
        subcategory_id: 6,
        purity: "91.75",
        type: "Weight",
        quantity: 1,
        gross_wt_in_g: 20.0,
        stone_wt_in_g: 0.5,
        net_wt_in_g: 19.5,
        purchase_rate: 12000.0,
        rate_per_g: 12000.0,
        total_amount: 234000.0,
        comments: "Mixed jewelry item",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("grnItems", null, {});
    await queryInterface.bulkDelete("grns", null, {});
  },
};
