const RoleRouter = require("./roleRoute");
const RolePermissionRouter = require("./rolesPermissionRoute");
const BranchRouter = require("./branchRoute");
const BankAccountRouter = require("./bankAccountRoute");
const KycDocumentRouter = require("./kycDocumentRoute");
const MaterialTypeRoute = require("./materialTypeRoute");
const CategoryRouter = require("./categoryRoute");
const SubcategoryRouter = require("./subcategoryRoute");
const VariantRouter = require("./variantRoute");
const ImageUploadRoute = require("./imageUploadRoute");
const UserLoginService = require("./userLoginRoute");
const VendorSpocDetailsRoute = require("./vendorSpocDetailsRoute");
const VendorRoutes = require("./vendorRoute");
const ProductRouter = require("./productRoute");
const GrnRouter = require("./grnRoute");
const ProductGrnInfoRoute = require("./productGrnInfoRoute");
const ProductAddOnRoute = require("./productAddOnRoute");
const CustomerRoute = require("./customerRoute");
const CountryRoute = require("./countryRoute");
const StateRoute = require("./stateRoute");
const DistrictRoute = require("./districtRoute");
const EmployeeRouter = require("./employeeRoute");
const InvoiceSettingsRouter = require("./invoiceSettingsRoute");
const SchemeRoute = require("./schemeRoute");
const UomRouter = require("./uomRoute");
const LedgerGroupRouter = require("./ledgerGroupRoute");
const LedgerRouter = require("./ledgerRoute");
const SuperAdminProfileRoute = require("./superAdminProfileRoute");
const ProductVariantRoute = require("./productVariantRoute");
const PurchaseOrderRoute = require("./purchaseOrderRoute");
const PurchaseReturnRoute = require("./purchaseReturnRoute");
const EnrollmentRoute = require("./enrollmentRoute");
const EmployeeIncentiveRoute = require("./employeeIncentiveRoute");
const EstimateBillRoute = require("./estimateBillRoute");
const SalesInvoiceRoute = require("./salesInvoiceBillRoute");
const QuotationRoute = require("./quotationRequestRoutes");
const HolidayRoute = require("./holidayRoutes");
const LeaveRoute = require("./leaveRoutes");
const LeaveTypeRoute = require("./leaveTypeRoutes");
const BillAdjustmentTypeRoute = require("./billAdjustmentTypeRoutes");
const OldJewelRoute = require("./oldJewelRoutes");
const SalesReturnRoute = require("./salesReturnRoute");
const JewelRepairRoute = require("./jewelRepairRoutes");
const StockTransferRoute = require("./stockTransferRoute");
const VendorPaymentRoute = require("./vendorPaymentRoute");
const ModuleRoute = require("./moduleRoute");
const EmployeeDepartmentRoute = require("./employeeDepartmentRoute");
const EmployeePermissionRoute = require("./employeePermissionRoutes");
const CartWishlistRoute = require("./cartWishlistRoute");
const OrderRoute = require("./orderRoute");
const CustomerAddressRoute = require("./customerAddressRoute");
const PurityRoute = require("./purityRoute");
const OfferRoute = require("./offerRoute");
const OfferPlanRoute = require("./offerPlanRoute");
const OfferApplicableTypeRoute = require("./offerApplicableTypeRoute");
const MaintenanceRoute = require("./maintenanceRoute");
const AuthRoute = require("./authRoute");
const StockManagementRoute = require("./stockManagementRoute");
const SalesManagementRoute = require("./salesManagementRoute");
const PayrollMasterRoute = require("./payrollMasterRoute");

module.exports = (app) => {
  app.use("/api/v1", RoleRouter);
  app.use("/api/v1", RolePermissionRouter);
  app.use("/api/v1", BranchRouter);
  app.use("/api/v1", BankAccountRouter);
  app.use("/api/v1", KycDocumentRouter);
  app.use("/api/v1", MaterialTypeRoute);
  app.use("/api/v1", CategoryRouter);
  app.use("/api/v1", SubcategoryRouter);
  app.use("/api/v1", ImageUploadRoute);
  app.use("/api/v1", UserLoginService);
  app.use("/api/v1", VendorSpocDetailsRoute);
  app.use("/api/v1", VendorRoutes);
  app.use("/api/v1", ProductRouter);

  app.use("/api/v1", GrnRouter);
  app.use("/api/v1", ProductGrnInfoRoute);
  app.use("/api/v1", VariantRouter);
  app.use("/api/v1", ProductAddOnRoute);
  app.use("/api/v1", CustomerRoute);
  app.use("/api/v1", CountryRoute);
  app.use("/api/v1", StateRoute);
  app.use("/api/v1", DistrictRoute);
  app.use("/api/v1", EmployeeRouter);
  app.use("/api/v1", InvoiceSettingsRouter);
  app.use("/api/v1", SchemeRoute);
  app.use("/api/v1", UomRouter);
  app.use("/api/v1", LedgerGroupRouter);
  app.use("/api/v1", LedgerRouter);
  app.use("/api/v1", SuperAdminProfileRoute);
  app.use("/api/v1", ProductVariantRoute);
  app.use("/api/v1", EnrollmentRoute);
  app.use("/api/v1", EmployeeIncentiveRoute);
  app.use("/api/v1", EstimateBillRoute);
  app.use("/api/v1", SalesInvoiceRoute);
  app.use("/api/v1", PurchaseOrderRoute);
  app.use("/api/v1", PurchaseReturnRoute);
  app.use("/api/v1", QuotationRoute);
  app.use("/api/v1", HolidayRoute);
  app.use("/api/v1", LeaveRoute);
  app.use("/api/v1", LeaveTypeRoute);
  app.use("/api/v1", BillAdjustmentTypeRoute);
  app.use("/api/v1", OldJewelRoute);
  app.use("/api/v1", SalesReturnRoute);
  app.use("/api/v1", JewelRepairRoute);
  app.use("/api/v1", StockTransferRoute);
  app.use("/api/v1", VendorPaymentRoute);
  app.use("/api/v1", ModuleRoute);
  app.use("/api/v1", EmployeeDepartmentRoute);
  app.use("/api/v1", EmployeePermissionRoute);
  app.use("/api/v1", CartWishlistRoute);
  app.use("/api/v1", OrderRoute);
  app.use("/api/v1", CustomerAddressRoute);
  app.use("/api/v1", PurityRoute);
  app.use("/api/v1", OfferRoute);
  app.use("/api/v1", OfferPlanRoute);
  app.use("/api/v1", OfferApplicableTypeRoute);
  app.use("/api/v1", MaintenanceRoute);
  app.use("/api/v1", AuthRoute);
  app.use("/api/v1", StockManagementRoute);
  app.use("/api/v1", SalesManagementRoute);
   app.use("/api/v1", PayrollMasterRoute);
};
