import { GoldenPlanImages, StudImg } from '@assets/Images';

const GoldRates = [
  {
    value: '24K Gold Rate - 110.00/g',
    label: '24K Gold Rate - 110.00/g',
  },
  {
    value: '22K Gold Rate - 100.00/g',
    label: '22K Gold Rate - 100.00/g',
  },
  {
    value: '18K Gold Rate - 85.00/g',
    label: '18K Gold Rate - 85.00/g',
  },
];
const cartData = [
  {
    id: '1',
    name: 'Oxidised Silver Earring',
    price: 2156,
    image: '/api/placeholder/200/200',
  },
  {
    id: '2',
    name: 'Gold Diamond Ring',
    price: 15500,
    originalPrice: 18000,
    image: '/api/placeholder/200/200',
  },
  {
    id: '3',
    name: 'Silver Necklace Set',
    price: 8900,
    image: '/api/placeholder/200/200',
  },
  {
    id: '4',
    name: 'Pearl Pendant',
    price: 4200,
    image: '/api/placeholder/200/200',
  },
  {
    id: '5',
    name: 'Traditional Bangles',
    price: 12000,
    originalPrice: 14000,

    image: '/api/placeholder/200/200',
  },
  {
    id: '6',
    name: 'Mangalsutra Design',
    price: 25000,
    image: '/api/placeholder/200/200',
  },
];
const categories = [
  { label: 'Drops & Danglers', count: 89 },
  { label: 'Studs', count: 32 },
  { label: 'Jhumkas', count: 18 },
  { label: 'Hoops', count: 25 },
];
const jewelryProducts = [
  {
    id: '7',
    name: 'Gold Coated Silver Earring',
    priceRange: '₹2,156 - 3,528',
    image: '/api/placeholder/250/250',
    category: 'earrings',
  },
  {
    id: '8',
    name: 'Flower Design Ring',
    price: 1156,
    image: '/api/placeholder/250/250',
    category: 'rings',
  },
  {
    id: '9',
    name: 'Mesh Bangle',
    price: 4556,
    image: '/api/placeholder/250/250',
    category: 'bangles',
  },
  {
    id: '10',
    name: 'Diamond Studs',
    priceRange: '₹2,156 - 3,528',
    image: '/api/placeholder/250/250',
    category: 'earrings',
  },
  {
    id: '11',
    name: 'Jhumka Earrings',
    price: 3200,
    image: '/api/placeholder/250/250',
    category: 'earrings',
  },
  {
    id: '12',
    name: 'Hoop Earrings',
    price: 1890,
    image: '/api/placeholder/250/250',
    category: 'earrings',
  },
];
const filterOptions: Record<string, string[]> = {
  Stone: ['CZ Stone', 'Kemp', 'MOP', 'Kundan'],
  Color: ['Gold Plated', 'Regular', 'Yellow'],
  Style: ['Oxidised'],
  ShopFor: ['Women', 'Men', 'Kids'],
};
const CardProductData = [
  {
    id: '1',
    name: 'Gold Necklace',
    price: 24999,
    image: StudImg,
    category: 'Jewelry',
  },
  {
    id: '2',
    name: 'Diamond Ring',
    price: 15999,
    image: StudImg,
    category: 'Rings',
  },
  {
    id: '3',
    name: 'Silver Bracelet',
    price: 4999,
    image: StudImg,
    category: 'Bracelets',
  },
  {
    id: '4',
    name: 'Pearl Earrings',
    price: 7999,
    image: StudImg,
    category: 'Earrings',
  },
  {
    id: '5',
    name: 'Pearl Earrings',
    price: 7999,
    image: StudImg,
    category: 'Earrings',
  },
  {
    id: '6',
    name: 'Pearl Earrings',
    price: 7999,
    image: StudImg,
    category: 'Earrings',
  },
  {
    id: '7',
    name: 'Pearl Earrings',
    price: 7999,
    image: StudImg,
    category: 'Earrings',
  },
];
const description = {
  text: `Elegant and timeless, our gold-plated earrings are crafted to elevate any look. With a luxurious finish and intricate designs, these pieces offer the perfect blend of style and sophistication, ideal for both everyday wear and special occasions.`,
};
// dummyProductDetails.ts
const productDetails = [
  { label: 'Purity', value: '99.9%' },
  { label: 'Grs Weight', value: '46.25 g' },
  { label: 'Net Weight', value: '46.25 g' },
  { label: 'Stone Weight', value: '2.25 g' },
  { label: 'Dimensions', value: 'Width: 1.2 cm   Length: 2.2 cm' },
];
const priceBreakupData = [
  { description: 'Silver', rate: '₹120.25', amount: '₹4,685' },
  { description: 'Making Charge', rate: '-', amount: '₹1,150' },
  { description: 'Tax', rate: '-', amount: '₹250' },
];

const totalAmount = '₹5,568';
const jewelleryCare = [
  'Do not wear when sweating',
  'Avoid perfume, lotion or sunscreen after wearing the jewel.',
  'Do not wear when washing.',
  'Avoid collide, grind or fire.',
  'Do not wear when sleeping.',
  'Put inside a plastic box when not in use. Avoid velvet box.',
  'Do not clean with chemicals.',
  'Use soft cloth to clean.',
];
const defaultAddresses = [
  {
    name: 'Charan',
    mobile: '+91 9944089638',
    addressLine1: '102, Baskiyalakudi Rd, Vincent Colony',
    addressLine2: 'R S Puram West, Coimbatore',
    state: 'Tamil Nadu',
    pin: '641002',
  },
];
const userDetails = {
  name: 'Charan',
  mobile: '+91 9944089896',
  email: 'charan142@gmail.com',
};

const CategoryData = [
  {
    id: '1',
    image: StudImg,
    name: 'Oxidised Silver Earring',
    category: 'Necklace',
    price: 2156,
    path: 'necklace/Pendant',
  },
  {
    id: '2',
    image: StudImg,
    name: 'Mesh Bangle',
    category: 'Earrings',
    price: 4556,
    path: 'earrings/Drops & Danglers',
  },
  {
    id: '3',
    image: StudImg,
    name: 'Gold Coated Silver Earring',
    category: 'Rings',
    price: 3156,
    path: 'rings/Plain Rings',
  },
  {
    id: '4',
    image: StudImg,
    name: 'Flower Design Ring',
    category: 'Bangles',
    price: 1156,
    path: 'bangles/Chain Bangle',
  },
  {
    id: '5',
    image: StudImg,
    name: 'Flower Design Ring',
    category: 'Anklets',
    price: 1156,
    path: 'earrings/Drops & Danglers',
  },
  {
    id: '6',
    image: StudImg,
    name: 'Flower Design Ring',
    category: 'Chains',
    price: 1156,
    path: 'earrings/Drops & Danglers',
  },
  {
    id: '7',
    image: StudImg,
    name: 'Flower Design Ring',
    category: 'Nose Pin',
    price: 1156,
    path: 'earrings/Drops & Danglers',
  },
  {
    id: '8',
    image: StudImg,
    name: 'Flower Design Ring',
    category: 'Mangalustra',
    price: 1156,
    path: 'mangalsutra/Traditional',
  },
  {
    id: '9',
    image: StudImg,
    name: 'Flower Design Ring',
    category: 'Stone Chain',
    price: 1156,
    path: 'earrings/Drops & Danglers',
  },
  {
    id: '10',
    image: StudImg,
    name: 'Flower Design Ring',
    category: 'Bracelet',
    price: 1156,
    path: 'earrings/Drops & Danglers',
  },
];

const order = [
  {
    orderNo: 'ORD_14886',
    qty: 2,
    date: '12/04/2025',
    status: 'Ready to Ship',
    items: [
      {
        img: StudImg,
        name: 'Gold Coated Silver Earring',
        price: '₹5,568',
        delivered: '14 May 2025',
      },
      {
        img: StudImg,
        name: 'Gold Coated Silver Earring',
        price: '₹5,568',
        delivered: '14 May 2025',
      },
    ],
  },
];
const wishlistItems = [
  {
    id: 1,
    name: 'Oxidised Silver Earring',
    price: '₹2,156',
    image: StudImg,
  },
  {
    id: 2,
    name: 'Gold Coated Silver Earring',
    price: '₹2,156 - 3,528',
    image: StudImg,
  },
  {
    id: 3,
    name: 'Flower Design Ring',
    price: '₹1,156',
    image: StudImg,
  },
];
const cartItems = [
  {
    id: 1,
    name: 'Gold Coated Silver Earring',
    price: 5568,
    weight: '46.25 g',
    qty: 1,
    image: StudImg,
  },
];
const CountryList = [
  { value: 1, label: 'India' },
  { value: 2, label: 'USA' },
  { value: 3, label: 'UK' },
  { value: 4, label: 'Canada' },
  { value: 5, label: 'Australia' },
];
const StateList = [
  { value: 1, label: 'Tamil Nadu' },
  { value: 2, label: 'Kerala' },
  { value: 3, label: 'Karnataka' },
  { value: 4, label: 'Andhra Pradesh' },
  { value: 5, label: 'Telangana' },
];
const DistrictList = [
  { value: 1, label: 'Chennai' },
  { value: 2, label: 'Coimbatore' },
  { value: 3, label: 'Madurai' },
  { value: 4, label: 'Salem' },
  { value: 5, label: 'Erode' },
];

export const DistrictListBranch = [
  { value: 1, label: 'Karur' },
  { value: 2, label: 'Cbe' },
  { value: 3, label: 'Hosur' },
];
export const BranchStatus = [
  { value: 'Active', label: 'Active' },
  { value: 'Inactive', label: 'Inactive' },
];
export const BranchState = [
  { value: 1, label: 'Tamil Nadu' },
  { value: 2, label: 'Kerala' },
  { value: 3, label: 'Karnataka' },
];
export const visibilityData = [
  {
    value: 1,
    label: 'Public',
  },
  {
    value: 2,
    label: 'Public1',
  },
];
export const balanceType = [
  {
    value: 'Credit',
    label: 'Credit',
  },
  {
    value: 'Debit',
    label: 'Debit',
  },
];

export const paymentTerms = [
  { value: '10days', label: '10days' },
  { value: '15days', label: '15days' },
  { value: '20days', label: '20days' },
  { value: '25days', label: '25days' },
  { value: '30days', label: '30days' },
];

export const schemeData = [
  {
    id: 1,
    s_no: 1,
    material_type: 'Gold',
    scheme_name: 'Dhivyam Saving Scheme',
    scheme_type: 'Value Based',
    duration: '12 months',
    status: 'Active',
  },
];

const BranchRows = [
  {
    id: 1,
    s_no: 1,
    branch_id: 1,
    branchNo: 'CJ_SLM_001',
    name: 'KHM Silver',
    location: 'Salem',
    conatct_person: 'Gokul',
    contact_no: '9876543207',
    status: 'Active',
  },
  {
    id: 2,
    s_no: 2,
    branch_id: 2,
    branchNo: 'CJ_COV_001',
    name: 'Sri Velli Alangaram',
    location: 'Thanjavur',
    conatct_person: 'Sanjay',
    contact_no: '9944556677',
    status: 'Active',
  },
  {
    id: 3,
    s_no: 3,
    branch_id: 3,
    branchNo: 'CJ_COV_002',
    name: 'Annapoorani Velli Chemmal',
    location: 'Coimbatore',
    conatct_person: 'Sarath',
    contact_no: '9003123456',
    status: 'Active',
  },
  {
    id: 4,
    s_no: 4,
    branch_id: 4,
    branchNo: 'CJ_COV_003',
    name: 'Annapoorani Velli Chemmal',
    location: 'Coimbatore',
    conatct_person: 'Sarath',
    contact_no: '9003123456',
    status: 'Active',
  },
  {
    id: 5,
    s_no: 5,
    branch_id: 5,
    branchNo: 'CJ_COV_004',
    name: 'Aathira Silver Mart',
    location: 'Madurai',
    conatct_person: 'Madhy',
    contact_no: '9003123456',
    status: 'Active',
  },
  {
    id: 6,
    s_no: 6,
    branch_id: 6,
    branchNo: 'CJ_COV_005',
    name: 'MoonMist Jewels',
    location: 'Pondicherry',
    conatct_person: 'Madhy',
    contact_no: '9003123456',
    status: 'Active',
  },
];

const CountryRows = [
  {
    id: 1,
    s_no: 1,
    country: 'India',
    country_id: 1,
    short_name: 'IN',
    currency_symbol: '@',
    status: 'Active',
  },
];

const StateRows = [
  {
    id: 1,
    country: 'India',
    state: 'Tamil Nadu',
    state_code: '33',
  },
  {
    id: 2,
    country: 'India',
    state: 'Tamil Nadu',
    state_code: '33',
  },
];

const UOMRows = [
  {
    id: 1,
    s_no: 1,
    uom_id: 'UOM001',
    uom_name: 'grams',
    short_code: 'gm',
    status: 'Active',
  },
  {
    id: 2,
    s_no: 2,
    uom_id: 'UOM002',
    uom_name: 'kilogram',
    short_code: 'kg',
    status: 'Deactive',
  },
];

const MaterialTypeRows = [
  {
    id: 1,
    s_no: 1,
    material_type: 'Gold',
    image: GoldenPlanImages,
  },
  {
    id: 2,
    s_no: 2,
    material_type: 'Silver',
    image: GoldenPlanImages,
  },
];
const TagPrintingRows = [
  {
    id: 1,
    s_no: 1,
    sku_id: 'PRID-005',
    hsn_code: '89651478',
    product_name: 'Flower Design Earrings',
    product_image_url: StudImg,
    purity: '99.9 %',
    grs_weight: '20 g',
    net_weight: '20 g',
  },
  {
    id: 2,
    s_no: 2,
    sku_id: 'PRID-006',
    hsn_code: '88759698',
    product_name: 'Bowl',
    product_image_url: StudImg,
    purity: '99.9 %',
    grs_weight: '20 g',
    net_weight: '20 g',
  },
  {
    id: 3,
    s_no: 3,
    sku_id: 'PRID-007',
    hsn_code: '22589687',
    product_name: 'Modern Ring',
    product_image_url: StudImg,
    purity: '99.9 %',
    grs_weight: '20 g',
    net_weight: '20 g',
  },
  {
    id: 4,
    s_no: 4,
    sku_id: 'PRID-007',
    hsn_code: '22589687',
    product_name: 'Diamond Design Necklace',
    product_image_url: StudImg,
    purity: '99.9 %',
    grs_weight: '20 g',
    net_weight: '20 g',
  },
  {
    id: 5,
    s_no: 5,
    sku_id: 'PRID-007',
    hsn_code: '22589687',
    product_name: 'New Bricks Bangles',
    product_image_url: StudImg,
    purity: '99.9 %',
    grs_weight: '20 g',
    net_weight: '20 g',
  },
];
const materialTypeOptions = [
  { label: 'Gold', value: 'gold' },
  { label: 'Silver', value: 'silver' },
  { label: 'Platinum', value: 'platinum' },
];
const categoryOptions = [
  { label: 'Earring', value: 'earring' },
  { label: 'Ring', value: 'ring' },
  { label: 'Necklace', value: 'necklace' },
];

const subCategoryOptions = [
  { label: 'Stud', value: 'stud' },
  { label: 'Hoop', value: 'hoop' },
  { label: 'Drop', value: 'drop' },
];
const grnOptions = [
  { label: 'GRN_58/24-25', value: 'grn_58_24_25' },
  { label: 'GRN_59/24-25', value: 'grn_59_24_25' },
];

const CategoryRows = [
  {
    id: 1,
    s_no: 1,
    material_type: 'Gold',
    category_name: 'Earrings',
    image: StudImg,
  },
  {
    id: 2,
    s_no: 2,
    material_type: 'Silver',
    category_name: 'Idols',
    image: StudImg,
  },
  {
    id: 3,
    s_no: 3,
    material_type: 'Diamond',
    category_name: 'Rings',
    image: StudImg,
  },
];

const SubCategoryRows = [
  {
    id: 1,
    s_no: 1,
    material_type: 'Silver',
    category_name: 'Earrings',
    sub_category_name: 'studs',
    reorder_level: 20,
    price: 20,
    margin: 20,
    image: StudImg,
  },
];

const VariantRows = [
  {
    id: 1,
    s_no: 1,
    variant_type: 'Stone Type',
    value: 'CZ Stone, Kundan',
    variantData: [{ variantName: 'CZ Stone' }, { variantName: 'kundan' }],
  },
];

const OfferData = [
  {
    id: 1,
    s_no: 1,
    offer_id: 'OFR 05/24-25',
    offer_plan: 'Conditional Offer',
    offer_type: 'Percentage',
    offer_value: '3%',
    validity: '02/09/2025 - 22/09/2025',
    description: 'Get 20 % Offer for gold jewellery',
    status: 'active',
  },
  {
    id: 2,
    s_no: 2,
    offer_id: 'OFR 05/24-25',
    offer_plan: 'Conditional Offer',
    offer_type: 'Percentage',
    offer_value: '3%',
    validity: '02/09/2025 - 22/09/2025',
    description: 'Get 20 % Offer for gold jewellery',
    status: 'active',
  },
  {
    id: 3,
    s_no: 3,
    offer_id: 'OFR 05/24-25',
    offer_plan: 'Conditional Offer',
    offer_type: 'Percentage',
    offer_value: '3%',
    validity: '02/09/2025 - 22/09/2025',
    description: 'Get 20 % Offer for gold jewellery',
    status: 'active',
  },
  {
    id: 4,
    s_no: 4,
    offer_id: 'OFR 05/24-25',
    offer_plan: 'Conditional Offer',
    offer_type: 'Percentage',
    offer_value: '3%',
    validity: '02/09/2025 - 22/09/2025',
    description: 'Get 20 % Offer for gold jewellery',
    status: 'inactive',
  },
];

export const selectDialogData = [
  {
    id: 1,
    s_no: 1,
    material_type: 'Gold',
    category: 'Earrings',
    isSelected: true,
    sub_category: 'Studs',
  },
  {
    id: 2,
    s_no: 2,
    material_type: 'Silver',
    category: 'Chain',
    isSelected: false,
    sub_category: 'Ring',
  },
];

const vendorListData = [
  {
    id: 1,
    s_no: 1,
    vendor: 'Golden Hub Pvt., Ltd.,',
    vendor_id: 'VEN 01/24-25',
    material_type: 'Gold',
    contact_person: 'Gokul',
    contact_no: '+919755523240',
    branch: 'Coimbatore',
    createdBy: 'Admin',
    created_location: 'Chennai',
  },
  {
    id: 2,
    s_no: 2,
    material_type: 'Gold',
    contact_person: 'Sarath',
    vendor: 'Golden Hub Pvt., Ltd.,',
    vendor_id: 'VEN 01/24-25',
    contact_no: '+919755523240',
    branch: 'Coimbatore',
    createdBy: 'Admin',
    created_location: 'Chennai',
  },
  {
    id: 3,
    s_no: 3,
    material_type: 'Gold Silver',
    contact_person: 'Kalai',
    vendor: 'Golden Hub Pvt., Ltd.,',
    vendor_id: 'VEN 01/24-25',
    contact_no: '+919755523240',
    branch: 'Salem',
    createdBy: 'Admin',
    created_location: 'Salem',
  },
  {
    id: 4,
    s_no: 4,
    material_type: 'Gold Silver',
    contact_person: 'Kalai Selvi',
    vendor: 'Golden Hub Pvt., Ltd.,',
    vendor_id: 'VEN 01/24-25',
    contact_no: '+919755523240',
    branch: 'Chennai',
    createdBy: 'Super Admin',
    created_location: '',
  },
  {
    id: 5,
    s_no: 5,
    material_type: 'Diamond',
    contact_person: 'Gokul Kumar',
    contact_no: '+919755523240',
    vendor: 'Golden Hub Pvt., Ltd.,',
    vendor_id: 'VEN 01/24-25',
    branch: 'Coimbatore',
    createdBy: 'Admin',
    created_location: 'Chennai',
  },
];

export const ProductListRows = [
  {
    id: 1,
    s_no: 1,
    sku_id: 'SKU_1257',
    hsn_no: '85785988',
    image: StudImg,
    name: 'Elegant Silver Stud',
    purity: '92.5%',
    weight: '12.25 g',
    quantity: '50',
  },
  {
    id: 2,
    s_no: 2,
    sku_id: 'SKU_1258',
    hsn_no: '85785989',
    image: StudImg,
    name: 'Golden Necklace',
    purity: '22K',
    weight: '25.50 g',
    quantity: '30',
  },
  {
    id: 3,
    s_no: 3,
    sku_id: 'SKU_1259',
    hsn_no: '85785990',
    image: StudImg,
    name: 'Diamond Ring',
    purity: '18K',
    weight: '5.75 g',
    quantity: '40',
  },
  {
    id: 4,
    s_no: 4,
    sku_id: 'SKU_1260',
    hsn_no: '85785991',
    image: StudImg,
    name: 'Platinum Chain',
    purity: '95%',
    weight: '18.10 g',
    quantity: '20',
  },
  {
    id: 5,
    s_no: 5,
    sku_id: 'SKU_1261',
    hsn_no: '85785992',
    image: StudImg,
    name: 'Rose Gold Bracelet',
    purity: '18K',
    weight: '15.80 g',
    quantity: '25',
  },
];

export const varientTypes = [
  { label: 'Finish', value: 1 },
  { label: 'Occassion ', value: 2 },
  { label: 'Shop For', value: 3 },
];

export const varientValues = [
  { label: 'Regular', value: 1 },
  { label: 'Women ', value: 2 },
];

const GRNData = [
  {
    id: 1,
    s_no: 1,
    date: '12/04/2025',
    grn_no: 'GRN_58/24-25',
    vendor_code: 'VEN 01/24-25',
    vendor_name: 'Sri Velli Alangaram',
    vendor_logo: null,
    order: 'ORD_14886',
    order_no: '125.5 g',
    updated_date: '0.00 g',
    yet_to_update: '0 g',
    created_by: 'Gokul',
    created_by_avatar: null,
    created_role: 'Admin',
    status: 'Pending',
  },
  {
    id: 2,
    s_no: 2,
    date: '15/02/2025',
    grn_no: 'GRN 02/24-25',
    vendor_code: 'VEN 02/24-25',
    vendor_name: 'Sri Velli Alangaram',
    vendor_logo: null,
    order: 'ORD_14887',
    order_no: '125.5 g',
    updated_date: '0.00 g',
    yet_to_update: '0 g',
    created_by: 'Gokul',
    created_by_avatar: null,
    created_role: 'Manager',
    status: 'Completed',
  },
  {
    id: 3,
    s_no: 3,
    date: '12/04/2025',
    grn_no: 'GRN_59/24-25',
    vendor_code: 'VEN 03/24-25',
    vendor_name: 'Shiva Silver Suppliers',
    vendor_logo: null,
    order: 'ORD_144587',
    order_no: '125.5 g',
    updated_date: '0.00 g',
    yet_to_update: '0 g',
    created_by: 'Gokul',
    created_by_avatar: null,
    created_role: 'Admin',
    status: 'Pending',
  },
  {
    id: 4,
    s_no: 4,
    date: '12/04/2025',
    grn_no: 'GRN_59/24-25',
    vendor_code: 'VEN 04/24-25',
    vendor_name: 'Sri Velli Alangaram',
    vendor_logo: null,
    order: 'ORD_14887',
    order_no: '125.5 g',
    updated_date: '0.00 g',
    yet_to_update: '0 g',
    created_by: 'Gokul',
    created_by_avatar: null,
    created_role: 'Supervisor',
    status: 'Pending',
  },
];

const purchaseOrderOptions = [
  { label: 'PO-1001', value: 'PO-1001' },
  { label: 'PO-1002', value: 'PO-1002' },
  { label: 'PO-1003', value: 'PO-1003' },
  { label: 'PO-1004', value: 'PO-1004' },
];
const vendorOptions = [
  { label: 'VEN 01/24-25', value: 'VEN 01/24-25' },
  { label: 'VEN 02/24-25', value: 'VEN 02/24-25' },
  { label: 'VEN 03/24-25', value: 'VEN 03/24-25' },
  { label: 'VEN 04/24-25', value: 'VEN 04/24-25' },
];
const OrderNameOptions = [
  { label: 'Anand B', value: 'Anand B' },
  { label: 'Kavya S', value: 'Kavya S' },
];

const MaterialTypeOptions = [
  { label: 'Gold', value: 'Gold' },
  { label: 'Silver', value: 'Silver' },
  { label: 'Platinum', value: 'Platinum' },
  { label: 'Diamond', value: 'Diamond' },
];
const QuotationListData = [
  {
    id: 1,
    s_no: 1,
    request_date: '12/02/1995',
    qr_id: 'QR 54/24-25',
    vendor_name: 'Shiva Silver Suppliers',
    expiry_date: '12/04/1995',
    quantity: 50,
    item_details: [
      {
        value: 1,
        label: 'Earrings',
      },
      {
        value: 2,
        label: 'Ring',
      },
    ],
    status: 'Received',
  },
  {
    id: 2,
    s_no: 2,
    request_date: '12/02/1995',
    qr_id: 'QR 54/24-25',
    vendor_name: 'Shiva Silver Suppliers',
    expiry_date: '12/04/1995',
    quantity: 50,
    item_details: [
      {
        value: 1,
        label: 'Earrings',
      },
      {
        value: 2,
        label: 'Ring',
      },
    ],
    status: 'Pending',
  },
  {
    id: 3,
    s_no: 3,
    request_date: '12/02/1995',
    qr_id: 'QR 54/24-25',
    vendor_name: 'Shiva Silver Suppliers',
    expiry_date: '12/04/1995',
    quantity: 50,
    item_details: [
      {
        value: 1,
        label: 'Earrings',
      },
      {
        value: 2,
        label: 'Ring',
      },
    ],
    status: 'Pending',
  },
  {
    id: 4,
    s_no: 4,
    request_date: '12/02/1995',
    qr_id: 'QR 54/24-25',
    vendor_name: 'Shiva Silver Suppliers',
    expiry_date: '12/04/1995',
    quantity: 50,
    item_details: [
      {
        value: 1,
        label: 'Earrings',
      },
      {
        value: 2,
        label: 'Ring',
      },
    ],
    status: 'Partially Received',
  },
  {
    id: 5,
    s_no: 5,
    request_date: '12/02/1995',
    qr_id: 'QR 54/24-25',
    vendor_name: 'Shiva Silver Suppliers',
    expiry_date: '12/04/1995',
    quantity: 50,
    item_details: [
      {
        value: 1,
        label: 'Earrings',
      },
      {
        value: 2,
        label: 'Ring',
      },
    ],
    status: 'Rejected',
  },
];

const ReceiveQuotationList = [
  {
    id: 1,
    s_no: 1,
    Qut_id: 'QUT 54/24-25',
    expiry_date: '16/02/2025',
    qr_id: 'QR 54/24-25',
    vendor_name: 'Shiva Silver Suppliers',
    items: [
      {
        value: 1,
        label: 'Earrings',
      },
      {
        value: 2,
        label: 'Ring',
      },
    ],
  },
  {
    id: 2,
    s_no: 2,
    Qut_id: 'QUT 54/24-25',
    expiry_date: '16/02/2025',
    qr_id: 'QR 54/24-25',
    vendor_name: 'Shiva Silver Suppliers',
    items: [
      {
        value: 1,
        label: 'Earrings',
      },
      {
        value: 2,
        label: 'Ring',
      },
    ],
  },
  {
    id: 3,
    s_no: 3,
    Qut_id: 'QUT 54/24-25',
    expiry_date: '16/02/2025',
    qr_id: 'QR 54/24-25',
    vendor_name: 'Shiva Silver Suppliers',
    items: [
      {
        value: 1,
        label: 'Earrings',
      },
      {
        value: 2,
        label: 'Ring',
      },
    ],
  },
];

const LedgerGroupRows = [
  {
    id: 1,
    s_no: 1,
    group_id: 'LGID001',
    group_name: 'Assets',
    ledger_name: 'Salary Payable',
  },
];

const HRManagementEmployeeRow = [
  {
    id: 1,
    s_no: 1,
    employee_name: 'Bessie Cooper',
    department: 'Operations',
    designation: 'Sales',
    employee_type: 'Full-Time',
    joined_date: '16/08/2013',
    employee_id: 'EMP_001',
    dob: '25/03/1992',
    bloodGroup: 'A+',
    gender: 'Female',
    employmentType: 'Full-Time',
    status: 'Active',
    mobile: '98765 43210',
    altMobile: '98888 77777',
    email: 'bessie.cooper@example.com',
    altContact: 'Riya',
    address: '23, Park Street, Chennai',
    state: 'Tamil Nadu',
    district: 'Chennai',
    country: 'India',
    pin: '600001',
    bankName: 'ICICI Bank',
    account: '123456789012',
    ifsc: 'ICIC0001256',
    branch: 'Anna Nagar',
    aadhaar_number: '1234 5678 9012',
    pan_number: 'ABCDE1234F',
    pan_file: 'pan_file.pdf',
    aadhaar_file: 'aadhaar_file.pdf',
  },
  {
    id: 2,
    s_no: 2,
    employee_name: 'Devon Lane',
    department: 'Manning',
    designation: 'Key Account Manager',
    employee_type: 'Full-Time',
    joined_date: '16/08/2013',
    employee_id: 'EMP_002',
    dob: '11/07/1990',
    bloodGroup: 'O+',
    gender: 'Male',
    employmentType: 'Full-Time',
    status: 'Active',
    mobile: '96547 32145',
    altMobile: '97878 99999',
    email: 'devon.lane@example.com',
    altContact: 'Ramesh',
    address: '14, MG Road, Bangalore',
    state: 'Karnataka',
    district: 'Bangalore Urban',
    country: 'India',
    pin: '560001',
    bankName: 'Axis Bank',
    account: '456789123654',
    ifsc: 'UTIB0003254',
    branch: 'Koramangala',
    aadhaar_number: '6543 2109 8765',
    pan_number: 'FGHIJ5678K',
    pan_file: 'pan_file.pdf',
    aadhaar_file: 'aadhaar_file.pdf',
  },
];

const attendanceData = [
  {
    s_no: 1,
    id: 1,
    employee_id: 'EMP_001',
    employee_name: 'Devon Lane',
    date: '10/05/2025',
    status: 'Present',
    clock_in: '09:00 AM',
    clock_out: '07:15 PM',
    production: '09h 00m',
    break: '00h 45m',
    over_time: '00h 20m',
    total_hours: '09h 20m',
  },
  {
    s_no: 2,
    id: 2,
    employee_id: 'EMP_002',
    employee_name: 'Bessie Cooper',
    date: '09/05/2025',
    status: 'Absent',
    clock_in: '-',
    clock_out: '-',
    production: '-',
    break: '-',
    over_time: '-',
    total_hours: '-',
  },
  {
    s_no: 3,
    id: 3,
    employee_id: 'EMP_003',
    employee_name: 'Sam Vishal',
    date: '08/05/2025',
    status: 'Present',
    clock_in: '09:00 AM',
    clock_out: '07:15 PM',
    production: '09h 00m',
    break: '00h 45m',
    over_time: '00h 20m',
    total_hours: '09h 20m',
  },
];

const receiptsData = [
  {
    id: 1,
    s_no: 1,
    month: 'October 2025',
    receipt_no: 'REC 11/24-25',
    date: '10/10/2025',
    credited_amount: 5000,
  },
  {
    id: 2,
    s_no: 2,
    month: 'September 2025',
    receipt_no: 'REC 12/24-25',
    date: '09/09/2025',
    credited_amount: 4000,
  },
  {
    id: 3,
    s_no: 3,
    month: 'August 2025',
    receipt_no: 'REC 13/24-25',
    date: '08/08/2025',
    credited_amount: 2000,
  },
  {
    id: 4,
    s_no: 4,
    month: 'July 2025',
    receipt_no: 'REC 14/24-25',
    date: '07/07/2025',
    credited_amount: 2500,
  },
  {
    id: 5,
    s_no: 5,
    month: 'June 2025',
    receipt_no: 'REC 15/24-25',
    date: '06/06/2025',
    credited_amount: 3500,
  },
];
// GRN View Dummy Data
const GRNViewData = {
  companyData: {
    address1: '74/1, W Poonurangam Rd',
    address2: 'R S Puram',
    city: 'Coimbatore',
    state: 'Tamil Nadu - 641002',
    mobile: '96545 569368',
    gstin: '33SSSCE563AIH',
  },
  supplierData: {
    name: 'Diamond Precious Metals Ltd',
    address1: '789, Bullion Market',
    address2: 'Zaveri Bazaar',
    city: 'Mumbai - 400002',
    mobile: 'Mobile No - 98765 43210',
    gst: 'GST No - 27XYZAB9876C1D2',
  },
  grnDetails: {
    date: '19/05/2025',
    grnNo: 'GRN 01/24-25',
    refNo: 'Po1024',
  },
  grnItems: [
    {
      id: 1,
      refNo: 'GRN001/01',
      material_type: 'Silver',
      category: 'Earrings',
      sub_category: 'Stud',
      description: 'Floral Studs',
      purity: '99.9%',
      material_price: '₹100.00',
      type: 'Piece',
      quantity: '5',
      gross_weight: '400.00',
      stone_weight: '20.00',
      others: 'Wood',
      others_weight: '10.00',
      others_value: '₹0.00',
      net_weight: '370.00',
      ordered_weight: '400.00',
      received_weight: '370.00',
      rate: '₹470.00',
      purchase_rate: '₹69,600.00',
      stone_rate: '₹15,000.00',
      making_charge: '₹80.00',
      rate_per_gram: '₹180.00',
      amount: '₹84,600.00',
    },
    {
      id: 2,
      refNo: 'GRN001/02',
      material_type: 'Silver',
      category: 'Earrings',
      sub_category: 'Stud',
      description: 'Cluster Studs',
      purity: '99.9%',
      material_price: '₹100.00',
      type: 'Piece',
      quantity: '8',
      gross_weight: '380.00',
      stone_weight: '20.00',
      others: '-',
      others_weight: '0.00',
      others_value: '₹0.00',
      net_weight: '370.00',
      ordered_weight: '380.00',
      received_weight: '370.00',
      rate: '₹470.00',
      purchase_rate: '₹30,000.00',
      stone_rate: '₹1,200.00',
      making_charge: '₹66.38',
      rate_per_gram: '₹166.38',
      amount: '₹78,200.00',
    },
    {
      id: 3,
      refNo: 'GRN001/03',
      material_type: 'Silver',
      category: 'Earrings',
      sub_category: 'Stud',
      description: 'Classic Studs',
      purity: '99.9%',
      material_price: '₹100.00',
      type: 'Piece',
      quantity: '7',
      gross_weight: '420.00',
      stone_weight: '25.00',
      others: '-',
      others_weight: '0.00',
      others_value: '₹0.00',
      net_weight: '395.00',
      ordered_weight: '420.00',
      received_weight: '395.00',
      rate: '₹470.00',
      purchase_rate: '₹30,000.00',
      stone_rate: '₹1,200.00',
      making_charge: '₹66.38',
      rate_per_gram: '₹166.38',
      amount: '₹78,200.00',
    },
    {
      id: 4,
      refNo: 'GRN001/04',
      material_type: 'Silver',
      category: 'Earrings',
      sub_category: 'Stud',
      description: 'Stud Piece',
      purity: '99.9%',
      material_price: '₹100.00',
      type: 'Piece',
      quantity: '5',
      gross_weight: '375.00',
      stone_weight: '20.00',
      others: '-',
      others_weight: '0.00',
      others_value: '₹0.00',
      net_weight: '355.00',
      ordered_weight: '375.00',
      received_weight: '355.00',
      rate: '₹470.00',
      purchase_rate: '₹30,000.00',
      stone_rate: '₹1,200.00',
      making_charge: '₹66.38',
      rate_per_gram: '₹166.38',
      amount: '₹78,200.00',
    },
    {
      id: 5,
      refNo: 'GRN001/05',
      material_type: 'Silver',
      category: 'Earrings',
      sub_category: 'Stud',
      description: 'Stud Weight',
      purity: '99.9%',
      material_price: '₹100.00',
      type: 'Weight',
      quantity: '10',
      gross_weight: '365.00',
      stone_weight: '25.00',
      others: '-',
      others_weight: '0.00',
      others_value: '₹0.00',
      net_weight: '350.00',
      ordered_weight: '365.00',
      received_weight: '350.00',
      rate: '₹470.00',
      purchase_rate: '₹15,000.00',
      stone_rate: '₹150.00',
      making_charge: '₹250.00',
      rate_per_gram: '₹250.00',
      amount: '₹1,17,500.00',
    },
    {
      id: 6,
      refNo: 'GRN001/06',
      material_type: 'Silver',
      category: 'Earrings',
      sub_category: 'Stud',
      description: 'Stud Weight',
      purity: '99.9%',
      material_price: '₹100.00',
      type: 'Weight',
      quantity: '10',
      gross_weight: '380.00',
      stone_weight: '25.00',
      others: '-',
      others_weight: '0.00',
      others_value: '₹0.00',
      net_weight: '355.00',
      ordered_weight: '380.00',
      received_weight: '355.00',
      rate: '₹470.00',
      purchase_rate: '₹30,000.00',
      stone_rate: '₹1,200.00',
      making_charge: '₹150.00',
      rate_per_gram: '₹166.38',
      amount: '₹1,18,700.00',
    },
    {
      id: 7,
      refNo: 'GRN001/07',
      material_type: 'Silver',
      category: 'Earrings',
      sub_category: 'Stud',
      description: 'Stud Weight',
      purity: '99.9%',
      material_price: '₹100.00',
      type: 'Weight',
      quantity: '10',
      gross_weight: '380.00',
      stone_weight: '25.00',
      others: '-',
      others_weight: '0.00',
      others_value: '₹0.00',
      net_weight: '355.00',
      ordered_weight: '380.00',
      received_weight: '355.00',
      rate: '₹470.00',
      purchase_rate: '₹30,000.00',
      stone_rate: '₹1,200.00',
      making_charge: '₹150.00',
      rate_per_gram: '₹166.38',
      amount: '₹1,18,700.00',
    },
    {
      id: 8,
      refNo: 'GRN001/08',
      material_type: 'Others',
      category: 'Beads',
      sub_category: 'Bronze Beads',
      description: 'Beads Piece',
      purity: '₹',
      material_price: '₹100.00',
      type: 'Piece',
      quantity: '5',
      gross_weight: '300.00',
      stone_weight: '20.00',
      others: '-',
      others_weight: '0.00',
      others_value: '₹0.00',
      net_weight: '270.00',
      ordered_weight: '300.00',
      received_weight: '270.00',
      rate: '₹470.00',
      purchase_rate: '₹800.00',
      stone_rate: '₹0.00',
      making_charge: '₹100.00',
      rate_per_gram: '₹100.00',
      amount: '₹800.00',
    },
  ],
  summary: {
    subTotal: '₹25,55,220.00',
    sgstPercentage: '1.5 %',
    sgstAmount: '₹290.00',
    cgstPercentage: '1.5 %',
    cgstAmount: '₹290.00',
    discountPercentage: '2 %',
    discountAmount: '₹115.00',
    totalAmount: '₹25,55,220.00',
    inWords: 'Twenty Five Lakh Fifty Five Thousand Two Hundred Twenty Only',
    totalReceivedWeight: '2,820.00 g',
    totalOrderedWeight: '3,000.00 g',
    totalQuantity: '60',
    totalGrossWeight: '3,000.00',
    totalStoneWeight: '180.00',
    totalOthersWeight: '10.00',
    totalOthersValue: '₹0.00',
    totalNetWeight: '2,820.00',
  },
  remarks:
    'Lorem ipsum dolor sit amet. Ut adipisci corrupti vel repudiandae culpa id enim ipsum vel expedita sint. Aut odio recusandae et aliquam dolor eum eligendi doloribus cum perspiciatis quia est quae asperiores. Et ullam officiis et doloribus dolorem aut laborum cupiditate eos inventore.',
  paymentDetails: {
    cardAmount: '₹15,000.00',
    cashAmount: '₹5,000.00',
    upiAmount: '₹1,465.00',
    transactionNumber: 'TXN123456789012',
  },
};
const employeeList = [
  {
    id: 1,
    name: 'Bessie Cooper',
    employee: 'EMP 01/24-25',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    branch: 'Thangaselvi Silver',
    department: 'Sales',
    designation: 'Manager',
    mobile_no: '9098900986',
    joining_date: '12/02/2025',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Devon Lane',
    employee: 'EMP 02/24-25',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    branch: 'Velli Maligai',
    department: 'Marketing',
    designation: 'Manager',
    mobile_no: '8989700987',
    joining_date: '15/02/2025',
    status: 'Active',
  },
  {
    id: 3,
    name: 'Albert Flores',
    employee: 'EMP 03/24-25',
    avatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    branch: 'Sri Velli Alangaram',
    department: 'Sales',
    designation: 'Staff',
    mobile_no: '7899935443',
    joining_date: '20/02/2025',
    status: 'Deactivate',
  },
  {
    id: 4,
    name: 'Eleanor Pena',
    employee: 'EMP 04/24-25',
    avatar: 'https://randomuser.me/api/portraits/men/46.jpg',
    branch: 'Aathira Silver Mart',
    department: 'Security',
    designation: 'Staff',
    mobile_no: '8989077654',
    joining_date: '25/02/2025',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Leslie Alexander',
    employee: 'EMP 05/24-25',
    avatar: 'https://randomuser.me/api/portraits/women/47.jpg',
    branch: 'Annapoorani Velli Chemmal',
    department: 'Billing',
    designation: 'Cashier',
    mobile_no: '9000987654',
    joining_date: '03/03/2025',
    status: 'Active',
  },
  {
    id: 6,
    name: 'Jenny Wilson',
    employee: 'EMP 06/24-25',
    avatar: 'https://randomuser.me/api/portraits/women/48.jpg',
    branch: 'ShineCraft Silver',
    department: 'Security',
    designation: 'Security Supervisor',
    mobile_no: '9858969858',
    joining_date: '12/02/2025',
    status: 'Active',
  },
  {
    id: 7,
    name: 'Cody Fisher',
    employee: 'EMP 07/24-25',
    branch: 'VelvetSilver',
    department: 'Marketing',
    designation: 'Staff',
    mobile_no: '7968585877',
    joining_date: '12/02/2025',
    status: 'Active',
  },
  {
    id: 8,
    name: 'Darlene Robertson',
    employee: 'EMP 08/24-25',
    branch: 'MoonMist Jewels',
    department: 'Security',
    designation: 'Security Guard',
    mobile_no: '5896987858',
    joining_date: '12/02/2025',
    status: 'Active',
  },
  {
    id: 9,
    name: 'Jerome Bell',
    employee: 'EMP 09/24-25',
    branch: 'PureAura Silver',
    department: 'Marketing',
    designation: 'Staff',
    mobile_no: '9587896987',
    joining_date: '12/02/2025',
    status: 'Active',
  },
  {
    id: 10,
    name: 'Floyd Miles',
    employee: 'EMP 10/24-25',
    branch: 'JewelPetal Silver',
    department: 'Marketing',
    designation: 'Staff',
    mobile_no: '9685859678',
    joining_date: '12/02/2025',
    status: 'Active',
  },
];
const roleData = [
  {
    id: 1,
    department: 'Admin',
    Roles: 'Super Admin',
    members: 1,
    access: 'Access to General, Master, Purchase Management, HR Management',
  },
  {
    id: 2,
    department: 'Branch Admin',
    Roles: 'Branch Admin',
    members: 4,
    access: 'Access to General, Purchase Management, HR Management',
  },
  {
    id: 3,
    department: 'Inventory',
    Roles: 'HR Manager',
    members: 2,
    access: 'Access to HR Management',
  },
  {
    id: 4,
    department: 'Branch Admin',
    Roles: 'Security',
    members: 3,
    access: 'Access to General',
  },
  {
    id: 5,
    department: 'Inventory',
    Roles: 'IT/Administrator',
    members: 4,
    access: 'Access to General, Master',
  },
];
const incentive = [
  {
    id: 1,
    role: 'Branch Admin',
    sales_target: '> ₹10,00,000',
    incentive_type: 'Percentage',
    incentives: '2%',
  },
  {
    id: 2,
    role: 'Sales Head',
    sales_target: '≥ ₹5,00,000',
    incentive_type: 'Percentage',
    incentives: '2%',
  },
  {
    id: 3,
    role: 'Sales Person',
    sales_target: '> ₹2,00,000',
    incentive_type: 'Rupees',
    incentives: '₹1,500.00',
  },
  {
    id: 4,
    role: 'Senior Executive',
    sales_target: '> ₹3,00,000',
    incentive_type: 'Percentage',
    incentives: '3%',
  },
  {
    id: 5,
    role: 'Marketing Manager',
    sales_target: '> ₹8,00,000',
    incentive_type: 'Rupees',
    incentives: '₹2,000.00',
  },
];
const CustomerRows = [
  {
    customer_id: 1,
    s_no: 1,
    customerNo: 'CID 01/24-25',
    customerName: 'Gokul',
    mobileNumber: '9876543204',
    noOfOrder: 2,
    mode: 'Offline',
    branch: 'HKM Branch',
    purchaseAmount: '14,00,000',
    schemeDetails: 'Yes',
    accountOpening: 'Yes',
  },
  {
    customer_id: 2,
    s_no: 2,
    customerNo: 'CID 02/24-25',
    customerName: 'Madhy',
    mobileNumber: '9876543210',
    noOfOrder: 3,
    mode: 'Online',
    branch: '-',
    purchaseAmount: '12,00,000',
    schemeDetails: '-',
    accountOpening: '-',
  },
  {
    customer_id: 3,
    s_no: 3,
    customerNo: 'CID 03/24-25',
    customerName: 'Kalai',
    mobileNumber: '9876543203',
    noOfOrder: 1,
    mode: 'Offline',
    branch: 'Silver Craft Jewels',
    purchaseAmount: '12,00,000',
    schemeDetails: '-',
    accountOpening: '-',
  },
  {
    customer_id: 4,
    s_no: 4,
    customerNo: 'CID 04/24-25',
    customerName: 'Sarith',
    mobileNumber: '9876543206',
    noOfOrder: 5,
    mode: 'Online',
    branch: '-',
    purchaseAmount: '10,00,000',
    schemeDetails: 'Yes',
    accountOpening: 'Yes',
  },
  {
    customer_id: 5,
    s_no: 5,
    customerNo: 'CID 05/24-25',
    customerName: 'Sanjay',
    mobileNumber: '9876543202',
    noOfOrder: 3,
    mode: 'Offline',
    branch: 'Silver Craft Jewels',
    purchaseAmount: '14,00,000',
    schemeDetails: 'Yes',
    accountOpening: 'Yes',
  },
  {
    customer_id: 6,
    s_no: 6,
    customerNo: 'CID 06/24-25',
    customerName: 'Kannan',
    mobileNumber: '9876543201',
    noOfOrder: 4,
    mode: 'Offline',
    branch: 'HKM Branch',
    purchaseAmount: '10,00,000',
    schemeDetails: '-',
    accountOpening: '-',
  },
  {
    customer_id: 7,
    s_no: 7,
    customerNo: 'CID 07/24-25',
    customerName: 'Kishore',
    mobileNumber: '9876543209',
    noOfOrder: 3,
    mode: 'Offline',
    branch: 'HKM Branch',
    purchaseAmount: '7,00,000',
    schemeDetails: 'Yes',
    accountOpening: 'Yes',
  },
  {
    customer_id: 8,
    s_no: 8,
    customerNo: 'CID 08/24-25',
    customerName: 'Arvind',
    mobileNumber: '9876543208',
    noOfOrder: 1,
    mode: 'Online',
    branch: '-',
    purchaseAmount: '10,00,000',
    schemeDetails: '-',
    accountOpening: '-',
  },
  {
    customer_id: 9,
    s_no: 9,
    customerNo: 'CID 09/24-25',
    customerName: 'Kathir',
    mobileNumber: '9876543205',
    noOfOrder: 3,
    mode: 'Online',
    branch: '-',
    purchaseAmount: '14,00,000',
    schemeDetails: '-',
    accountOpening: '-',
  },
  {
    customer_id: 10,
    s_no: 10,
    customerNo: 'CID 10/24-25',
    customerName: 'Surathy',
    mobileNumber: '9876543207',
    noOfOrder: 2,
    mode: 'Offline',
    branch: '-',
    purchaseAmount: '7,00,000',
    schemeDetails: '-',
    accountOpening: '-',
  },
];
const sampleOrderData = [
  {
    id: 1,
    s_no: 1,
    date: '12/02/2025',
    invoice_no: 'INV 01/24-25',
    product_name: 'Silver Ring',
    sub_products: '1 Other Products',
    quantity: 2,
    total_amount: 14000,
    branch: '-',
    order_type: 'Online',
  },
  {
    id: 2,
    s_no: 2,
    date: '15/02/2025',
    invoice_no: 'INV 02/24-25',
    product_name: 'Silver Coin 10g',
    sub_products: null,
    quantity: 1,
    total_amount: 14000,
    branch: 'Coimbatore',
    order_type: 'Offline',
  },
  {
    id: 3,
    s_no: 3,
    date: '20/02/2025',
    invoice_no: 'INV 03/24-25',
    product_name: 'Anklet - Traditional',
    sub_products: '1 Other Products',
    quantity: 2,
    total_amount: 14000,
    branch: 'Coimbatore',
    order_type: 'Offline',
  },
  {
    id: 4,
    s_no: 4,
    date: '25/02/2025',
    invoice_no: 'INV 04/24-25',
    product_name: 'Chain - Box Design',
    sub_products: null,
    quantity: 1,
    total_amount: 14000,
    branch: 'Avadi',
    order_type: 'Offline',
  },
  {
    id: 5,
    s_no: 5,
    date: '03/03/2025',
    invoice_no: 'INV 05/24-25',
    product_name: 'Bangle Set',
    sub_products: null,
    quantity: 1,
    total_amount: 14000,
    branch: '-',
    order_type: 'Online',
  },
];
const sampleCustomerData = [
  {
    id: 1,
    s_no: 1,
    customer_no: 'CID 01/24-25',
    customer_name: 'Gokul',
    mobile_number: '9876543204',
    no_of_order: 2,
    mode: 'Offline',
    branch: 'HKM Branch',
    purchase_amount: 14300,
    scheme_details: 'Yes',
  },
  {
    id: 2,
    s_no: 2,
    customer_no: 'CID 02/24-25',
    customer_name: 'Madhy',
    mobile_number: '9876543216',
    no_of_order: 3,
    mode: 'Online',
    branch: '-',
    purchase_amount: 12500,
    scheme_details: '-',
  },
  {
    id: 3,
    s_no: 3,
    customer_no: 'CID 03/24-25',
    customer_name: 'Kalai',
    mobile_number: '9876543203',
    no_of_order: 1,
    mode: 'Offline',
    branch: 'Silver Craft Jewels',
    purchase_amount: 12500,
    scheme_details: '-',
  },
  {
    id: 4,
    s_no: 4,
    customer_no: 'CID 04/24-25',
    customer_name: 'Selath',
    mobile_number: '9876543206',
    no_of_order: 5,
    mode: 'Online',
    branch: '-',
    purchase_amount: 10500,
    scheme_details: 'Yes',
  },
  {
    id: 5,
    s_no: 5,
    customer_no: 'CID 05/24-25',
    customer_name: 'Sanjay',
    mobile_number: '9876543202',
    no_of_order: 3,
    mode: 'Offline',
    branch: 'Silver Craft Jewels',
    purchase_amount: 14300,
    scheme_details: 'Yes',
  },
];

const PurchaseData = [
  {
    id: 1,
    s_no: 1,
    date: '12/04/2025',
    po_no: 'PO 01/24-25',
    branch_name: 'KHM Silver',
    vendor_name: 'Sri Velli Alangaram',
    weight: '10.25g',
    created_by: 'Chennai',
    created_role: 'Admin',
    status: 'Offline',
  },
  {
    id: 2,
    s_no: 2,
    date: '12/03/2025',
    po_no: 'PO 02/24-25',
    branch_name: 'Velli Maligai',
    vendor_name: 'Shiva Silver Suppliers',
    weight: '8.25g',
    created_by: 'Chennai',
    created_role: 'Admin',
    status: 'Online',
  },
];
const PurchaseReturnData = [
  {
    id: 1,
    s_no: 1,
    date: '12/04/2025',
    pr_no: 'PR 01/24-25',
    branch_name: 'KHM Silver',
    vendor_name: 'Sri Velli Alangaram',
    quantity: 10,
    weight: '10.25g',
    created_by: 'Chennai',
    created_role: 'Admin',
  },
  {
    id: 2,
    s_no: 2,
    date: '12/03/2025',
    pr_no: 'PR 02/24-25',
    branch_name: 'Velli Maligai',
    vendor_name: 'Shiva Silver Suppliers',
    quantity: 10,
    weight: '8.25g',
    created_by: 'Chennai',
    created_role: 'Admin',
  },
];
const VendorNameOptions = [
  { label: 'Sai Precious Metals', value: 'Sai Precious Metals' },
  { label: 'Sri Lakshmi Jewellers', value: 'Sri Lakshmi Jewellers' },
  { label: 'Anand Gold Works', value: 'Anand Gold Works' },
  { label: 'Meenakshi Silver Crafts', value: 'Meenakshi Silver Crafts' },
];
const purchaseReturnOptions = [
  { label: 'PR 01/24-25', value: 'PR 01/24-25' },
  { label: 'PR 02/24-25', value: 'PR 02/24-25' },
  { label: 'PR 03/24-25', value: 'PR 03/24-25' },
  { label: 'PR 04/24-25', value: 'PR 04/24-25' },
];
const priceBreakup = [
  { description: '92.5 Silver', rate: '₹120.25', amount: '₹4,685' },
  { description: 'GST 3%', rate: '-', amount: '₹30' },
];
const totalAmt = '₹4,715';
const productSpecifications = [
  { label: 'Purity', value: '99.9%' },

  { label: 'Dimensions', value: 'Width: 1.2 cm   Length: 2.2 cm' },
];

const PayrollData = {
  company: {
    address: '74/1, W Poonurangam Rd',
    area: 'R S Puram',
    city: 'Coimbatore',
    state: 'Tamil Nadu - 641002',
    mobile: '96545 569368',
    gstin: '33SSSCE5634IH',
  },
  employee: {
    name: 'Sam Vishal',
    id: 'EMP 03/24-25',
    pfNumber: 'PF142548896',
  },
  branch: 'HMK Silver',
  dateCredited: '05/05/2025',
  totalDays: 28,
  totalLeave: 3,
  overtime: '05 Hrs',
  month: 'March 2025',
  earnings: [
    { type: 'Basic Salary', amount: '₹20,000.00' },
    { type: 'HRA Allowance', amount: '₹0.00' },
    { type: 'DA Allowance', amount: '₹0.00' },
    { type: 'Bonus', amount: '₹0.00' },
    { type: 'Incentives', amount: '₹1,000.00' },
  ],
  deductions: [
    { type: 'PF', amount: '₹0.00' },
    { type: 'Professional Tax', amount: '₹0.00' },
    { type: 'TDS', amount: '₹0.00' },
    { type: 'Bonus', amount: '₹0.00' },
  ],
  inWords: 'Twenty One Thousand Only',
  paymentMode: 'Account Transfer',
  transactionNo: 'REC1257875656JBHAD',
};

const dummyIncentivesData = [
  {
    id: 1,
    s_no: 1,
    employee_name: 'Bessie Cooper',
    employee_id: 'EMP 01/24-25',
    designation: 'Sales Executive',
    sales_target: '₹10,00,000',
    incentives: '₹ 5000',
    image: '',
  },
  {
    id: 2,
    s_no: 2,
    employee_name: 'Devon Lane',
    employee_id: 'EMP 02/24-25',
    designation: 'Key Account Manager',
    sales_target: '₹5,00,000',
    incentives: '₹ 4000',
    image: '',
  },
  {
    id: 3,
    s_no: 3,
    employee_name: 'Albert Flores',
    employee_id: 'EMP 03/24-25',
    designation: 'Channel Sales Manager',
    sales_target: '₹2,00,000',
    incentives: '₹ 2000',
  },
];
const PurchaseReturnsData = {
  companyData: {
    address1: '74/1, W Poonurangam Rd',
    address2: 'R S Puram',
    city: 'Coimbatore',
    state: 'Tamil Nadu - 641002',
    mobile: '96545 569368',
    gstin: '33SSSCE563AIH',
  },
  supplierData: {
    name: 'Diamond Precious Metals Ltd',
    address1: '789, Bullion Market',
    address2: 'Zaveri Bazaar',
    city: 'Mumbai - 400002',
    mobile: 'Mobile No - 98765 43210',
    gst: 'GST No - 27XYZAB9876C1D2',
  },
  grnDetails: {
    date: '19/05/2025',
    grnNo: 'GRN 01/24-25',
    refNo: 'Po1024',
  },
  grnItems: [
    {
      id: 1,
      material_type: 'Silver',
      category: 'Earrings',
      sub_category: 'Stud',
      description: 'Flower Stud',
      purity: '92.5 %',
      ordered_weight: '22.35 g',
      received_weight: '22.35g',
      rate: '₹10,525',
      amount: '₹21,000',
    },
  ],
  summary: {
    subTotal: '₹3,05,170',
    sgst: { percentage: '0 %', amount: '0.00' },
    cgst: { percentage: '2 %', amount: '6,103.40' },
    discount: { percentage: '2 %', amount: '6,103.40' },
    totalAmount: '₹3,05,170',
    inWords: 'Three Lakh Five Thousand One Hundred Seventy Only',
  },
  remarks:
    'Lorem ipsum dolor sit amet. Ut adipisci corrupti vel repudiandae culpa id enim ipsum vel expedita sint. Aut odio recusandae et aliquam dolor eum eligendi doloribus cum perspiciatis quia est quae asperiores. Et ullam officiis et doloribus dolorem aut laborum cupiditate eos inventore.',
  paymentDetails: {
    cardAmount: '₹15,000.00',
    cashAmount: '₹5,000.00',
    upiAmount: '₹1,465.00',
    transactionNumber: 'TXN123456789012',
  },
};
const PurchaseOrderData = {
  companyData: {
    address1: '74/1, W Poonurangam Rd',
    address2: 'R S Puram',
    city: 'Coimbatore',
    state: 'Tamil Nadu - 641002',
    mobile: '96545 569368',
    gstin: '33SSSCE563AIH',
  },
  supplierData: {
    name: 'Sai Precious Metals',
    address1: '123/1, West street, KM Nagar',

    city: 'Salem - 625869',
    mobile: 'Mobile No - 98765 43210',
    gst: 'GST No - 27XYZAB9876C1D2',
  },

  purchaseDetails: {
    date: '19/05/2025',
    grnNo: 'PO 05/24-25',
    // grnNo: 'GRN 01/24-25',
    // refNo: 'Po1024',
  },
  purchaseItems: [
    {
      id: 1,
      material_type: 'Silver',
      category: 'Earrings',
      sub_category: 'Stud',
      description: 'Flower Stud',
      purity: '92.5 %',
      ordered_weight: '22.35 g',
      received_weight: '22.35g',
      rate: '₹10,525',
      amount: '₹21,000',
    },
  ],
  summary: {
    subTotal: '₹3,05,170',
    sgst: { percentage: '0 %', amount: '0.00' },
    cgst: { percentage: '2 %', amount: '6,103.40' },
    discount: { percentage: '2 %', amount: '6,103.40' },
    totalAmount: '₹3,05,170',
    inWords: 'Three Lakh Five Thousand One Hundred Seventy Only',
  },
  remarks:
    'Lorem ipsum dolor sit amet. Ut adipisci corrupti vel repudiandae culpa id enim ipsum vel expedita sint. Aut odio recusandae et aliquam dolor eum eligendi doloribus cum perspiciatis quia est quae asperiores. Et ullam officiis et doloribus dolorem aut laborum cupiditate eos inventore.',
};

const DivyamGoldSaverData = [
  {
    id: 1,
    s_no: 1,
    date_scheme: '05/06/2025',
    scheme_id: 'SCHM001',
    customer_name: 'Arun Kumar',
    mobile_number: '9876543210',
    saving_scheme: 'Gold Savings Plan',
    Installment_Amount: '₹2,000',
    due1: 3,
    due2: 12,
    mode: 'Offline',
    branch: 'HKM Branch',
  },
  {
    id: 2,
    s_no: 2,
    date_scheme: '15/07/2025',
    scheme_id: 'SCHM002',
    customer_name: 'Priya Sharma',
    mobile_number: '9123456780',
    saving_scheme: 'Diamond Growth Plan',
    Installment_Amount: '₹5,000',
    due1: 10,
    due2: 12,
    mode: 'Online',
    branch: '-',
  },
  {
    id: 3,
    s_no: 3,
    date_scheme: '25/06/2025',
    scheme_id: 'SCHM003',
    customer_name: 'Vignesh R',
    mobile_number: '9008765432',
    saving_scheme: 'Silver Smart Saver',
    Installment_Amount: '₹3,000',
    due1: 3,
    due2: 12,
    mode: 'offline',
    branch: 'HKM Branch',
  },
  {
    id: 4,
    s_no: 4,
    date_scheme: '29/06/2025',
    scheme_id: 'SCHM004',
    customer_name: 'Sneha L',
    mobile_number: '8887766554',
    saving_scheme: 'Platinum Scheme',
    Installment_Amount: '₹10,000',
    due1: 5,
    due2: 12,
    mode: 'Offline',
    branch: 'Silver Craft Jewels',
  },
  {
    id: 5,
    s_no: 5,
    date_scheme: '05/08/2025',
    scheme_id: 'SCHM005',
    customer_name: 'Ramesh Babu',
    mobile_number: '9443322110',
    saving_scheme: 'Gold Plus Plan',
    Installment_Amount: '₹7,000',
    due1: 5,
    due2: 12,
    mode: 'Online',
    branch: '-',
  },
];
const ViewQuotationData = [
  {
    id: 1,
    s_no: 1,
    material_type: 'Gold',
    category: 'Necklace',
    sub_category: 'Nakshtra',
    product_description: 'Others',
    purity: '99.9%',
    weight: '50.00g',
    quantity: '50',
    rate: '₹12,555.00',
    amount: '₹12,555.00',
  },
  {
    id: 2,
    s_no: 2,
    material_type: 'Gold',
    category: 'Earrings',
    sub_category: 'Studs',
    product_description: 'Flower Design',
    purity: '99.9%',
    weight: '50.00g',
    quantity: '50',
    rate: '₹12,555.00',
    amount: '₹12,555.00',
  },
];

const LeaveListDatas = [
  {
    id: 1,
    s_no: 1,
    employee_id: 'EMP001',
    employee_name: 'Arjun Kumar',
    designation: 'Sales Executive',
    leave_date: '2025-10-10',
    leave_type: 'Casual Leave',
    reason: 'Family function',
  },
  {
    id: 2,
    s_no: 2,
    employee_id: 'EMP002',
    employee_name: 'Divya',
    designation: 'HR Manager',
    leave_date: '2025-10-11',
    leave_type: 'Sick Leave',
    reason: 'Fever and cold',
  },
  {
    id: 3,
    s_no: 3,
    employee_id: 'EMP003',
    employee_name: 'Kavin',
    designation: 'Software Engineer',
    leave_date: '2025-10-12',
    leave_type: 'Paid Leave',
    reason: 'Personal work',
  },
];
const HolidaysListData = [
  {
    id: 1,
    s_no: 1,
    name: 'New Year',
    date: '01 Jan 2024',
    description: 'First day of new year',
  },
  {
    id: 2,
    s_no: 2,
    name: 'Martin Luther King Jr. Day',
    date: '02 Jan 2024',
    description: 'Celebrating the civil rights leader',
  },
  {
    id: 3,
    s_no: 3,
    name: 'President’s',
    date: '09 Jan 2024',
    description: 'Honoring past US Presidents',
  },
  {
    id: 4,
    s_no: 4,
    name: 'Good Friday',
    date: '29 Jan 2024',
    description: 'Holidays before Easter',
  },
];
const payrollDummyData = [
  {
    id: 1,
    s_no: 1,
    employee_name: 'John Doe',
    employee_id: 'EMP003',
    month: 'October 2025',
    receipt_no: 'REC-001',
    date: '2025-10-28',
    amount_credited: '₹45,000',
  },
  {
    id: 2,
    s_no: 2,
    employee_name: 'Priya Sharma',
    employee_id: 'EMP003',
    month: 'October 2025',
    receipt_no: 'REC-002',
    date: '2025-10-29',
    amount_credited: '₹52,000',
  },
  {
    id: 3,
    s_no: 3,
    employee_name: 'Rahul Mehta',
    employee_id: 'EMP003',
    month: 'September 2025',
    receipt_no: 'REC-003',
    date: '2025-09-30',
    amount_credited: '₹40,500',
  },
  {
    id: 4,
    s_no: 4,
    employee_name: 'Anita Raj',
    employee_id: 'EMP003',
    month: 'August 2025',
    receipt_no: 'REC-004',
    date: '2025-08-31',
    amount_credited: '₹48,200',
  },
];
const orderData = [
  {
    id: 1,
    date_time: '22/09/2025 12:52 pm',
    customer_name: 'Kishore Kumar',
    mobile_number: '9658495896',
    product_name: 'Elegant Silver Stud',
    avatar: 'https://randomuser.me/api/portraits/women/47.jpg',
    total_products: 2,
    total_amount: '₹2,890',
    order_status: 'Remainder Sent',
  },
  {
    id: 2,
    date_time: '22/09/2025 12:52 pm',
    customer_name: 'Sunil Kumar',
    mobile_number: '9587895698',
    product_name: 'Silver Jhumkas',
    avatar: 'https://randomuser.me/api/portraits/women/47.jpg',
    total_products: 1,
    total_amount: '₹3,780',
    order_status: 'Not Contacted',
  },
];
const revenueBranchData = [
  {
    id: 1,
    description: 'INV 258/24-25',
    cash: '₹12,000',
    upi: '₹12,000',
    card: '₹12,000',
    total_amount: '₹12,000',
    opening_stock: '23,832',
    sold: '3,478',
    old_silver: '389',
    closing_stock: '20,743',
  },
  {
    id: 2,
    description: 'INV 258/24-25',
    cash: '₹25,000',
    upi: '₹25,000',
    card: '₹25,000',
    total_amount: '₹25,000',
    opening_stock: '23,832',
    sold: '3,478',
    old_silver: '389',
    closing_stock: '20,743',
  },
  {
    id: 3,
    description: 'INV 258/24-25',
    cash: '₹20,475',
    upi: '₹20,475',
    card: '₹20,475',
    total_amount: '₹20,475',
    opening_stock: '23,832',
    sold: '3,478',
    old_silver: '389',
    closing_stock: '20,743',
  },
];
const revenueData = [
  {
    id: 1,
    branch_name: 'KHM Silver',
    cash: '₹12,000',
    upi: '₹12,000',
    card: '₹12,000',
    total_amount: '₹12,000',
    opening_stock: '23,832',
    sales: '3,478',
    old_silver: '389',
    closing_stock: '20,743',
  },
  {
    id: 2,
    branch_name: 'Velli Maligai',
    cash: '₹25,000',
    upi: '₹25,000',
    card: '₹25,000',
    total_amount: '₹25,000',
    opening_stock: '23,832',
    sales: '3,478',
    old_silver: '389',
    closing_stock: '20,743',
  },
  {
    id: 3,
    branch_name: 'Sri Velli Alangaram',
    cash: '₹20,475',
    upi: '₹20,475',
    card: '₹20,475',
    total_amount: '₹20,475',
    opening_stock: '23,832',
    sales: '3,478',
    old_silver: '389',
    closing_stock: '20,743',
  },
];
const assetManagementData = [
  {
    id: 1,
    s_no: 1,
    asset_id: 'AST 25/24-25',
    asset_category: 'Machinery ',
    asset_name: 'Meena Silvers Shop',
    status: 'Update Pending',
    branch_from: 'HKM Silvers',
  },
  {
    id: 2,
    s_no: 2,
    asset_id: 'AST 25/24-25',
    asset_category: 'Display & Fixtures',
    asset_name: 'Rings Sizer',
    status: 'In Use',
    branch_from: 'HKM Silvers',
  },
  {
    id: 3,
    s_no: 3,
    asset_id: 'AST 25/24-25',
    asset_category: 'Display',
    asset_name: 'Meena Silvers Shop',
    status: 'In Use',
    branch_from: 'HKM Silvers',
  },
  {
    id: 4,
    s_no: 4,
    asset_id: 'AST 21/24-25',
    asset_category: 'Networking',
    asset_name: 'Rings Sizer',
    status: 'In Use',
    branch_from: 'HKM Silvers',
  },
  {
    id: 5,
    s_no: 5,
    asset_id: 'AST 21/24-25',
    asset_category: 'Display & Fixtures',
    asset_name: 'Rings Sizer',
    status: 'Under Maintenance',
    branch_from: 'HKM Silvers',
  },
];
const MaintenanceHistory = [
  {
    id: 1,
    s_no: 1,
    date: '12/02/2025',
    maintenance_type: 'General',
    technician_name: 'Kannan',
    machine_performance: 'Good',
    remarks: 'General',
  },
  {
    id: 2,
    s_no: 2,
    date: '15/02/2025',
    maintenance_type: 'Periodic',
    technician_name: 'Kishore',
    machine_performance: 'Good',
    remarks: 'General',
  },
  {
    id: 3,
    s_no: 3,
    date: '12/02/2025',
    maintenance_type: 'General',
    technician_name: 'Kannan',
    machine_performance: 'Good',
    remarks: 'General',
  },
  {
    id: 4,
    s_no: 4,
    date: '12/02/2025',
    maintenance_type: 'General',
    technician_name: 'Kishore',
    machine_performance: 'Good',
    remarks: 'General',
  },
  {
    id: 5,
    s_no: 5,
    date: '12/02/2025',
    maintenance_type: 'General',
    technician_name: 'Kannan',
    machine_performance: 'Good',
    remarks: 'General',
  },
];
const StockList = [
  {
    id: 1,
    s_no: 1,
    branch_name: 'ThangaSelvi Silver',
    gold_quantity: '1545',
    gold_value: '₹1,10,011',
    silver_quantity: '2485',
    silver_value: '₹1,10,020',
    old_jewel_weight: '45.52 g',
  },
  {
    id: 2,
    s_no: 2,
    branch_name: 'Velli Maligai',
    gold_quantity: '1545',
    gold_value: '₹1,10,011',
    silver_quantity: '2485',
    silver_value: '₹1,10,020',
    old_jewel_weight: '45.52 g',
  },
  {
    id: 3,
    s_no: 3,
    branch_name: 'Sri Velli Alangaram',
    gold_quantity: '1545',
    gold_value: '₹1,10,011',
    silver_quantity: '2485',
    silver_value: '₹1,10,020',
    old_jewel_weight: '45.52 g',
  },
  {
    id: 4,
    s_no: 4,
    branch_name: 'Aathira Silver Mart',
    gold_quantity: '1545',
    gold_value: '₹1,10,011',
    silver_quantity: '2485',
    silver_value: '₹1,10,020',
    old_jewel_weight: '45.52 g',
  },
  {
    id: 5,
    s_no: 5,
    branch_name: 'Annapoorani Velli Chemmal',
    gold_quantity: '1545',
    gold_value: '₹1,10,011',
    silver_quantity: '2485',
    silver_value: '₹1,10,020',
    old_jewel_weight: '45.52 g',
  },
  {
    id: 6,
    s_no: 6,
    branch_name: 'ShineCraft Silver',
    gold_quantity: '1545',
    gold_value: '₹1,10,011',
    silver_quantity: '2485',
    silver_value: '₹1,10,020',
    old_jewel_weight: '45.52 g',
  },
  {
    id: 7,
    s_no: 7,
    branch_name: 'VelvetSilver',
    gold_quantity: '1545',
    gold_value: '₹1,10,011',
    silver_quantity: '2485',
    silver_value: '₹1,10,020',
    old_jewel_weight: '45.52 g',
  },
  {
    id: 8,
    s_no: 8,
    branch_name: 'MoonMist Jewels',
    gold_quantity: '1545',
    gold_value: '₹1,13,011',
    silver_quantity: '1298',
    silver_value: '₹1,10,020',
    old_jewel_weight: '45.52 g',
  },
  {
    id: 9,
    s_no: 9,
    branch_name: 'PureAura Silver',
    gold_quantity: '1545',
    gold_value: '₹3,10,011',
    silver_quantity: '1978',
    silver_value: '₹5,10,020',
    old_jewel_weight: '45.52 g',
  },
  {
    id: 10,
    s_no: 10,
    branch_name: 'JewelPetal Silver',
    gold_quantity: '1545',
    gold_value: '₹26,15,011',
    silver_quantity: '1999',
    silver_value: '₹3,10,030',
    old_jewel_weight: '45.52 g',
  },
];
// Dummy dropdown data

const planOptions = [
  { label: 'Monthly Savings Plan', value: 1 },
  { label: 'Quarterly Savings Plan', value: 2 },
  { label: 'Yearly Savings Plan', value: 3 },
];

const identityProofOptions = [
  { label: 'Aadhaar Card', value: 'AADHAAR' },
  { label: 'PAN Card', value: 'PAN' },
  { label: 'Voter ID', value: 'VOTER_ID' },
  { label: 'Driving License', value: 'DL' },
  { label: 'Passport', value: 'PASSPORT' },
];

const nomineeRelationOptions = [
  { label: 'Father', value: 'FATHER' },
  { label: 'Mother', value: 'MOTHER' },
  { label: 'Wife', value: 'WIFE' },
  { label: 'Husband', value: 'HUSBAND' },
  { label: 'Son', value: 'SON' },
  { label: 'Daughter', value: 'DAUGHTER' },
  { label: 'Brother', value: 'BROTHER' },
  { label: 'Sister', value: 'SISTER' },
];
const BranchWiseData = [
  {
    id: 1,
    s_no: 1,
    branch_id: 'CJ_SLM_001',
    branch_name: 'Thangaselvi Silver',
    location: 'Chennai',
    gold_quantity: 1545,
    gold_value: '₹1,10,011',
    silver_quantity: 2485,
    silver_value: '₹1,10,020',
    old_jewel_weight: '45.52 g',
    total_stock_value: '₹2,20,031',
  },
  {
    id: 2,
    s_no: 2,
    branch_id: 'CJ_CHE_001',
    branch_name: 'Velli Maligai',
    location: 'Coimbatore',
    gold_quantity: 1545,
    gold_value: '₹2,10,340',
    silver_quantity: 2147,
    silver_value: '₹1,23,000',
    old_jewel_weight: '45.52 g',
    total_stock_value: '₹3,33,340',
  },
  {
    id: 3,
    s_no: 3,
    branch_id: 'CJ_MDY_001',
    branch_name: 'Sri Velli Alangaram',
    location: 'Madurai',
    gold_quantity: 1545,
    gold_value: '₹1,10,022',
    silver_quantity: 1958,
    silver_value: '₹95,010',
    old_jewel_weight: '45.52 g',
    total_stock_value: '₹2,05,032',
  },
  {
    id: 4,
    s_no: 4,
    branch_id: 'CJ_COV_001',
    branch_name: 'Anithra Silver Mart',
    location: 'Trichy',
    gold_quantity: 1545,
    gold_value: '₹5,10,019',
    silver_quantity: 5785,
    silver_value: '₹2,10,340',
    old_jewel_weight: '45.52 g',
    total_stock_value: '₹7,30,040',
  },
  {
    id: 5,
    s_no: 5,
    branch_id: 'CJ_ERD_001',
    branch_name: 'Ammapoorani Velli Chemmal',
    location: 'Salem',
    gold_quantity: 1545,
    gold_value: '₹1,10,020',
    silver_quantity: 1987,
    silver_value: '₹1,23,100',
    old_jewel_weight: '45.52 g',
    total_stock_value: '₹2,33,120',
  },
  {
    id: 6,
    s_no: 6,
    branch_id: 'CJ_ERD_002',
    branch_name: 'ShineCraft Silver',
    location: 'Erode',
    gold_quantity: 1545,
    gold_value: '₹1,10,029',
    silver_quantity: 2155,
    silver_value: '₹1,23,120',
    old_jewel_weight: '45.52 g',
    total_stock_value: '₹2,33,149',
  },
  {
    id: 7,
    s_no: 7,
    branch_id: 'CJ_CHE_002',
    branch_name: 'Vellest Silver',
    location: 'Chennai',
    gold_quantity: 1545,
    gold_value: '₹1,10,020',
    silver_quantity: 2627,
    silver_value: '₹1,20,360',
    old_jewel_weight: '45.52 g',
    total_stock_value: '₹2,30,380',
  },
  {
    id: 8,
    s_no: 8,
    branch_id: 'CJ_PDY_001',
    branch_name: 'MoonMart Jewels',
    location: 'Pondicherry',
    gold_quantity: 1545,
    gold_value: '₹3,10,000',
    silver_quantity: 1298,
    silver_value: '₹1,10,017',
    old_jewel_weight: '45.52 g',
    total_stock_value: '₹4,20,017',
  },
  {
    id: 9,
    s_no: 9,
    branch_id: 'CJ_TVL_001',
    branch_name: 'PureAura Silver',
    location: 'Tirunelveli',
    gold_quantity: 1545,
    gold_value: '₹1,10,010',
    silver_quantity: 1990,
    silver_value: '₹1,20,000',
    old_jewel_weight: '45.52 g',
    total_stock_value: '₹2,30,010',
  },
  {
    id: 10,
    s_no: 10,
    branch_id: 'CJ_TRL_001',
    branch_name: 'JewelPetal Silver',
    location: 'Tirupathi',
    gold_quantity: 1545,
    gold_value: '₹6,15,100',
    silver_quantity: 1999,
    silver_value: '₹3,10,030',
    old_jewel_weight: '45.52 g',
    total_stock_value: '₹9,25,130',
  },
];
export const branchWiseStockList = [
  {
    id: 1,
    category: 'Earrings',
    subCategory: 'Studs',
    skuId: 'SKU_SLM_524',
    product: 'Silver Dot Stud',
    purity: '99.9 %',
    grsWeight: '20 g',
    netWeight: '20 g',
    quantity: 1,
    image: '/images/earrings.png',
  },
  {
    id: 2,
    category: 'Idols',
    subCategory: 'Single Line',
    skuId: 'SKU_SLM_523',
    product: 'Moon Pebble',
    purity: '99.9 %',
    grsWeight: '05 g',
    netWeight: '05 g',
    quantity: 1,
    image: '/images/idol.png',
  },
  {
    id: 3,
    category: 'Rings',
    subCategory: 'Plain Rings',
    skuId: 'SKU_SLM_522',
    product: 'Everyday Elegance',
    purity: '99.9 %',
    grsWeight: '10 g',
    netWeight: '10 g',
    quantity: 1,
    image: '/images/ring.png',
  },
  {
    id: 4,
    category: 'Necklace',
    subCategory: 'Pendant',
    skuId: 'SKU_SLM_521',
    product: 'Temple Drop',
    purity: '99.9 %',
    grsWeight: '50 g',
    netWeight: '50 g',
    quantity: 1,
    image: '/images/necklace.png',
  },
  {
    id: 5,
    category: 'Bangles',
    subCategory: 'Antique Bangles',
    skuId: 'SKU_SLM_520',
    product: 'Antique Petal',
    purity: '99.9 %',
    grsWeight: '25 g',
    netWeight: '25 g',
    quantity: 1,
    image: '/images/bangle.png',
  },
  {
    id: 6,
    category: 'Accessories',
    subCategory: 'Silver Coins',
    skuId: 'SKU_SLM_519',
    product: 'Nova Studs',
    purity: '99.9 %',
    grsWeight: '25 g',
    netWeight: '25 g',
    quantity: 1,
    image: '/images/coin.png',
  },
  {
    id: 7,
    category: 'Necklace',
    subCategory: 'Pendant',
    skuId: 'SKU_SLM_518',
    product: 'Nova Studs',
    purity: '99.9 %',
    grsWeight: '25 g',
    netWeight: '25 g',
    quantity: 1,
    image: '/images/necklace.png',
  },
  {
    id: 8,
    category: 'Rings',
    subCategory: 'Plain Rings',
    skuId: 'SKU_SLM_517',
    product: 'Nova Studs',
    purity: '99.9 %',
    grsWeight: '25 g',
    netWeight: '25 g',
    quantity: 1,
    image: '/images/ring.png',
  },
  {
    id: 9,
    category: 'Earrings',
    subCategory: 'Studs',
    skuId: 'SKU_SLM_516',
    product: 'Nova Studs',
    purity: '99.9 %',
    grsWeight: '25 g',
    netWeight: '25 g',
    quantity: 1,
    image: '/images/earrings.png',
  },
];
const StockHandList = [
  {
    id: 1,
    s_no: 1,
    category_name: 'Earrings',
    sub_category: 'Studs',
    sku_id: 'SKU_SLM_524',
    product: 'Silver Dot Stud',
    purity: '99.9 %',
    grs_weight: '20 g',
    net_weight: '20 g',
    quantity: 1,
    image: '/images/earrings.png',
  },
  {
    id: 2,
    s_no: 2,
    category_name: 'Idols',
    sub_category: 'Single Line',
    sku_id: 'SKU_SLM_523',
    product: 'Moon Pebble',
    purity: '99.9 %',
    grs_weight: '05 g',
    net_weight: '05 g',
    quantity: 1,
    image: '/images/idol.png',
  },
  {
    id: 3,
    s_no: 3,
    category_name: 'Rings',
    sub_category: 'Plain Rings',
    sku_id: 'SKU_SLM_522',
    product: 'Everyday Elegance',
    purity: '99.9 %',
    grs_weight: '10 g',
    net_weight: '10 g',
    quantity: 1,
    image: '/images/ring.png',
  },
  {
    id: 4,
    s_no: 4,
    category_name: 'Necklace',
    sub_category: 'Pendant',
    sku_id: 'SKU_SLM_521',
    product: 'Temple Drop',
    purity: '99.9 %',
    grs_weight: '50 g',
    net_weight: '50 g',
    quantity: 1,
    image: '/images/necklace.png',
  },
  {
    id: 5,
    s_no: 5,
    category_name: 'Bangles',
    sub_category: 'Antique Bangles',
    sku_id: 'SKU_SLM_520',
    product: 'Antique Petal',
    purity: '99.9 %',
    grs_weight: '25 g',
    net_weight: '25 g',
    quantity: 1,
    image: '/images/bangle.png',
  },
  {
    id: 6,
    s_no: 6,
    category_name: 'Accessories',
    sub_category: 'Silver Coins',
    sku_id: 'SKU_SLM_519',
    product: 'Nova Studs',
    purity: '99.9 %',
    grs_weight: '25 g',
    net_weight: '25 g',
    quantity: 1,
    image: '/images/coin.png',
  },
  {
    id: 7,
    s_no: 7,
    category_name: 'Necklace',
    sub_category: 'Pendant',
    sku_id: 'SKU_SLM_518',
    product: 'Nova Studs',
    purity: '99.9 %',
    grs_weight: '25 g',
    net_weight: '25 g',
    quantity: 1,
    image: '/images/necklace.png',
  },
  {
    id: 8,
    s_no: 8,
    category_name: 'Rings',
    sub_category: 'Plain Rings',
    sku_id: 'SKU_SLM_517',
    product: 'Nova Studs',
    purity: '99.9 %',
    grs_weight: '25 g',
    net_weight: '25 g',
    quantity: 1,
    image: '/images/ring.png',
  },
  {
    id: 9,
    s_no: 9,
    category_name: 'Earrings',
    sub_category: 'Studs',
    sku_id: 'SKU_SLM_516',
    product: 'Nova Studs',
    purity: '99.9 %',
    grs_weight: '25 g',
    net_weight: '25 g',
    quantity: 1,
    image: '/images/earrings.png',
  },
];
const LowstockList = [
  { id: 1, s_no: 1, sub_category: 'Studs', low: 2, Action: 'Purchase Now' },
  { id: 2, s_no: 2, sub_category: 'Jhumkas', low: 4, Action: 'Purchase Now' },
  { id: 3, s_no: 3, sub_category: 'Danglers', low: 1, Action: 'Purchase Now' },
];
const OutofstockList = [
  {
    id: 1,
    s_no: 1,
    branch_name: 'ThangaSelvi Silver',
    sub_category: 'Studs',
    quantity: 3,
    Action: 'Purchase Now',
  },
  {
    id: 2,
    s_no: 2,
    branch_name: 'Velli Maligai',
    sub_category: 'Single Line',
    quantity: 2,
    Action: 'Purchase Now',
  },
  {
    id: 3,
    s_no: 3,
    branch_name: 'Sri Velli Alangaram',
    sub_category: 'Plain Rings',
    quantity: 4,
    Action: 'Purchase Now',
  },
];

const stockTransferList = [
  {
    id: 1,
    s_no: 1,
    transfer_no: 'TID/01/24-25',
    date: '12/02/2025',
    branch_from: 'HKM Silvers',
    branch_to: 'Meena Silvers Shop',
    approved_by: 'Admin Chennai',
    quantity: 5,
    weight: '10.25 Kg',
  },
  {
    id: 2,
    s_no: 2,
    transfer_no: 'TID/02/24-25',
    date: '15/02/2025',
    branch_from: 'HKM Silvers',
    branch_to: 'Meena Silvers Shop',
    approved_by: 'Admin Chennai',
    quantity: 10,
    weight: '8.24 Kg',
  },
  {
    id: 3,
    s_no: 3,
    transfer_no: 'TID/03/24-25',
    date: '20/02/2025',
    branch_from: 'HKM Silvers',
    branch_to: 'Meena Silvers Shop',
    approved_by: 'Admin Chennai',
    quantity: 2,
    weight: '12 Kg',
  },
];
const branchRows = [
  {
    id: 1,
    branch_name: 'KHM Silver',
    total_sales: '₹2,10,340',
    total_invoices: '458',
    total_amount: '₹1,02,000',
  },
  {
    id: 2,
    branch_name: 'Velli Maligai',
    total_sales: '₹3,10,030',
    total_invoices: '123',
    total_amount: '₹2,50,000',
  },
  {
    id: 3,
    branch_name: 'Sri Velli Alangaram',
    total_sales: '₹1,13,000',
    total_invoices: '234',
    total_amount: '₹2,04,750',
  },
  {
    id: 4,
    branch_name: 'Aathira Silver Mart',
    total_sales: '₹2,10,340',
    total_invoices: '436',
    total_amount: '₹1,90,200',
  },
];
const salesInvoiceData = [
  {
    id: 1,
    date: '19/05/2025',
    invoice_no: 'INV 01/24-25',
    customer_no: '9898990908',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '12.00',
    net_weight: '12.00',
    quantity: 2,
    order_type: 'Online',
    total_amount: 12000,
  },
  {
    id: 2,
    date: '19/05/2025',
    invoice_no: 'INV 02/24-25',
    customer_no: '9898990908',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '10.00',
    net_weight: '10.00',
    quantity: 4,
    order_type: 'Online',
    total_amount: 25000,
  },
  {
    id: 3,
    date: '19/05/2025',
    invoice_no: 'INV 03/24-25',
    customer_no: '9898990908',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '45.50',
    net_weight: '45.50',
    quantity: 5,
    order_type: 'Offline',
    total_amount: 20475,
  },
  {
    id: 4,
    date: '19/05/2025',
    invoice_no: 'INV 04/24-25',
    customer_no: '9898990908',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '30.00',
    net_weight: '30.00',
    quantity: 1,
    order_type: 'Offline',
    total_amount: 19200,
  },
  {
    id: 5,
    date: '19/05/2025',
    invoice_no: 'INV 05/24-25',
    customer_no: '9898990908',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '35.00',
    net_weight: '35.00',
    quantity: 2,
    order_type: 'Offline',
    total_amount: 18900,
  },
  {
    id: 6,
    date: '19/05/2025',
    invoice_no: 'INV 06/24-25',
    customer_no: '9898990908',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '5.50',
    net_weight: '5.50',
    quantity: 1,
    order_type: 'Offline',
    total_amount: 6188,
  },
  {
    id: 7,
    date: '19/05/2025',
    invoice_no: 'INV 07/24-25',
    customer_no: '9898990908',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '9.25',
    net_weight: '9.25',
    quantity: 1,
    order_type: 'Online',
    total_amount: 9900,
  },
  {
    id: 8,
    date: '19/05/2025',
    invoice_no: 'INV 08/24-25',
    customer_no: '9898990908',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '20.00',
    net_weight: '20.00',
    quantity: 3,
    order_type: 'Online',
    total_amount: 8000,
  },
  {
    id: 9,
    date: '19/05/2025',
    invoice_no: 'INV 09/24-25',
    customer_no: '9898990908',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '22.75',
    net_weight: '22.75',
    quantity: 2,
    order_type: 'Offline',
    total_amount: 13650,
  },
  {
    id: 10,
    date: '19/05/2025',
    invoice_no: 'INV 10/24-25',
    customer_no: '9898990908',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '60.00',
    net_weight: '60.00',
    quantity: 1,
    order_type: 'Offline',
    total_amount: 24000,
  },
];
const salesReturnData = [
  {
    id: 1,
    date_of_return: '19/05/2025',
    branch_name: 'KHM Silver',
    sales_return_id: 'SR 21/24-25',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '12.00',
    net_weight: '12.00',
    quantity: 1,
    total_amount: 12000,
  },
  {
    id: 2,
    date_of_return: '19/05/2025',
    branch_name: 'Velli Maligai',
    sales_return_id: 'SR 22/24-25',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '10.00',
    net_weight: '10.00',
    quantity: 1,
    total_amount: 25000,
  },
  {
    id: 3,
    date_of_return: '19/05/2025',
    branch_name: 'Sri Velli Alangaram',
    sales_return_id: 'SR 23/24-25',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '45.50',
    net_weight: '45.50',
    quantity: 1,
    total_amount: 20475,
  },
  {
    id: 4,
    date_of_return: '19/05/2025',
    branch_name: 'Aathira Silver Mart',
    sales_return_id: 'SR 24/24-25',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '30.00',
    net_weight: '30.00',
    quantity: 1,
    total_amount: 19200,
  },
  {
    id: 5,
    date_of_return: '19/05/2025',
    branch_name: 'Annapoorani Velli Chemmal',
    sales_return_id: 'SR 25/24-25',
    product_name: 'Silver Ring',
    other_products_count: 3,
    grs_weight: '35.00',
    net_weight: '35.00',
    quantity: 1,
    total_amount: 18900,
  },
];
const branchListData = [
  {
    id: 1,
    branch_no: 'CJ_SLM_001',
    branch_name: 'KHM Silver',
    location: 'Salem',
    branch_admin: 'Gokul',
    contact_number: '9876543207',
  },
  {
    id: 2,
    branch_no: 'CJ_CHE_001',
    branch_name: 'Velli Maligai',
    location: 'Madurai',
    branch_admin: 'Madhy',
    contact_number: '9876543208',
  },
  {
    id: 3,
    branch_no: 'CJ_TIY_001',
    branch_name: 'Sri Velli Alangaram',
    location: 'Trichy',
    branch_admin: 'Kalai',
    contact_number: '9876543209',
  },
  {
    id: 4,
    branch_no: 'CJ_COI_001',
    branch_name: 'Aathira Silver Mart',
    location: 'Coimbatore',
    branch_admin: 'Sarath',
    contact_number: '9876543210',
  },
  {
    id: 5,
    branch_no: 'CJ_TNJ_001',
    branch_name: 'Annapoorani Velli Chemmal',
    location: 'Thanjavur',
    branch_admin: 'Sanjay',
    contact_number: '9876543211',
  },
  {
    id: 6,
    branch_no: 'CJ_ERO_001',
    branch_name: 'ShineCraft Silver',
    location: 'Erode',
    branch_admin: 'Sarath Kumar',
    contact_number: '9876543212',
  },
  {
    id: 7,
    branch_no: 'CJ_CHN_001',
    branch_name: 'VelvetSilver',
    location: 'Chennai',
    branch_admin: 'Kishore',
    contact_number: '9876543213',
  },
  {
    id: 8,
    branch_no: 'CJ_PON_001',
    branch_name: 'MoonMist Jewels',
    location: 'Pondicherry',
    branch_admin: 'Aravind',
    contact_number: '9876543214',
  },
  {
    id: 9,
    branch_no: 'CJ_TIR_001',
    branch_name: 'PureAura Silver',
    location: 'Tirunelveli',
    branch_admin: 'Kathir',
    contact_number: '9876543215',
  },
  {
    id: 10,
    branch_no: 'CJ_PER_001',
    branch_name: 'JewelPetal Silver',
    location: 'Perambalur',
    branch_admin: 'Sarathy',
    contact_number: '9876543216',
  },
];
const branchStatsData = [
  {
    id: 1,
    branch_name: 'ThengaSeki Silver',
    sales_value: '65,276',
    purchase_value: '65,276',
    stock_value: '65,276',
    total_revenue: '65,276',
    total_employee: 123,
  },
  {
    id: 2,
    branch_name: 'Velli Maligui',
    sales_value: '82,786',
    purchase_value: '82,786',
    stock_value: '82,786',
    total_revenue: '82,786',
    total_employee: 34,
  },
  {
    id: 3,
    branch_name: 'Sri Velli Alengaram',
    sales_value: '87,972',
    purchase_value: '87,972',
    stock_value: '87,972',
    total_revenue: '87,972',
    total_employee: 243,
  },
  {
    id: 4,
    branch_name: 'Aathira Silver Matt',
    sales_value: '116,677',
    purchase_value: '116,677',
    stock_value: '116,677',
    total_revenue: '116,677',
    total_employee: 525,
  },
  {
    id: 5,
    branch_name: 'Amapogrami Velli Chemmali',
    sales_value: '70,801',
    purchase_value: '70,801',
    stock_value: '70,801',
    total_revenue: '70,801',
    total_employee: 435,
  },
  {
    id: 6,
    branch_name: 'ShineCraft Silver',
    sales_value: '95,208',
    purchase_value: '95,208',
    stock_value: '95,208',
    total_revenue: '95,208',
    total_employee: 458,
  },
  {
    id: 7,
    branch_name: 'VelwcSilver',
    sales_value: '57,950',
    purchase_value: '57,950',
    stock_value: '57,950',
    total_revenue: '57,950',
    total_employee: 67,
  },
  {
    id: 8,
    branch_name: 'MoorMist Jewels',
    sales_value: '24,181',
    purchase_value: '24,181',
    stock_value: '24,181',
    total_revenue: '24,181',
    total_employee: 87,
  },
];
const topBuyingData = [
  {
    id: 1,
    customer_id: 'CID 01/24-25',
    customer: 'Gokul',
    total_amount: ' 14,00,000',
  },
  {
    id: 2,
    customer_id: 'CID 03/24-25',
    customer: 'Madhy',

    total_amount: '12,00,000',
  },
  {
    id: 3,
    customer_id: 'CID 03/24-25',
    customer: 'Kalai',

    total_amount: '12,00,000',
  },
  {
    id: 4,
    customer_id: 'CID 04/24-25',
    customer: 'Sarath',

    total_amount: '10,00,000',
  },
  {
    id: 5,
    customer_id: 'CID 04/24-25',
    customer: 'Sarath k',

    total_amount: '10,00,000',
  },
];
const topEmployeeData = [
  {
    id: 1,
    employee_id: 'EMP 52/24-25',
    employee_name: 'kasimozhi',
    weight: '45.25 g',
    sales_amount: '45,258',
  },
  {
    id: 2,
    employee_id: 'EMP 55/7/24-25',
    employee_name: 'Ajith',
    weight: '40.25 g',
    sales_amount: '40,258',
  },
  {
    id: 3,
    employee_id: 'EMP 125/24-25',
    employee_name: 'Saravanan',
    weight: '38.25 g',
    sales_amount: '24,258',
  },
  {
    id: 4,
    employee_id: 'CDD 178/24-25',
    employee_name: 'Aadhavan',
    weight: '36.25 g',
    sales_amount: '20,258',
  },
  {
    id: 5,
    employee_id: 'CDD 247/24-25',
    employee_name: 'Suba',
    weight: '32.25 g',
    sales_amount: '18,258',
  },
];
const stockUpdateData = [
  {
    id: 1,
    date: '13/02/2025',
    material_type: 'Gold',
    category: 'Nocturnce',
    sub_category: 'Product',
    quantity: 20,
  },
  {
    id: 2,
    date: '13/02/2025',
    material_type: 'Gold',
    category: 'Earnings',
    sub_category: 'Earnings',
    quantity: 25,
  },
  {
    id: 3,
    date: '28/02/2025',
    material_type: 'Silver',
    category: 'Bings',
    sub_category: 'Bing',
    quantity: 65,
  },
  {
    id: 4,
    date: '28/02/2025',
    material_type: 'Silver',
    category: 'Benefits',
    sub_category: 'Benefits',
    quantity: 10,
  },
  {
    id: 5,
    date: '25/02/2025',
    material_type: 'Silver',
    category: 'Benefits',
    sub_category: 'Benefits',
    quantity: 10,
  },
];
const vendorsData = [
  {
    id: 1,
    vendor_name: 'Golden Hub Pvt., Ltd.',
    vendor_code: 'VEN1023',
    contact_person: 'Gokul',
    contact_number: '+919755523240',
    material_type: ['Gold', 'Silver'],
    branch: 'Chennai',
    created_by: 'Admin',
  },
  {
    id: 2,
    vendor_name: 'Shiva Silver Suppliers',
    vendor_code: 'VEN1024',
    contact_person: 'Sarath',
    contact_number: '+919755523241',
    material_type: ['Silver'],
    branch: 'Salem',
    created_by: 'Super Admin',
  },
  {
    id: 3,
    vendor_name: 'Jai Shree Jewels',
    vendor_code: 'VEN1025',
    contact_person: 'Kishore',
    contact_number: '+919755523242',
    material_type: ['Gold'],
    branch: 'Chennai',
    created_by: 'Admin',
  },
  {
    id: 4,
    vendor_name: 'Kailash Gold & Silver Mart',
    vendor_code: 'VEN1026',
    contact_person: 'Madhy',
    contact_number: '+919755523243',
    material_type: ['Gold', 'Silver'],
    branch: 'Super Admin',
    created_by: 'Admin',
  },
  {
    id: 5,
    vendor_name: 'Sai Precious Metals',
    vendor_code: 'VEN1027',
    contact_person: 'Kalai',
    contact_number: '+919755523244',
    material_type: ['Silver'],
    branch: 'Chennai',
    created_by: 'Super Admin',
  },
  {
    id: 6,
    vendor_name: 'Elegant Silver Works',
    vendor_code: 'VEN1028',
    contact_person: 'Sanjay',
    contact_number: '+919755523245',
    material_type: ['Silver'],
    branch: 'Salem',
    created_by: 'Admin',
  },
  {
    id: 7,
    vendor_name: 'Rajendra Metals Pvt. Ltd.',
    vendor_code: 'VEN1029',
    contact_person: 'Kannan',
    contact_number: '+919755523246',
    material_type: ['Gold', 'Silver'],
    branch: 'Chennai',
    created_by: 'Admin',
  },
  {
    id: 8,
    vendor_name: 'Kiran Casting Studio',
    vendor_code: 'VEN1030',
    contact_person: 'Aravind',
    contact_number: '+919755523247',
    material_type: ['Gold'],
    branch: 'Super Admin',
    created_by: 'Super Admin',
  },
  {
    id: 9,
    vendor_name: 'Golden Wrap & Co.',
    vendor_code: 'VEN1031',
    contact_person: 'Kathir',
    contact_number: '+919755523248',
    material_type: ['Gold', 'Silver'],
    branch: 'Chennai',
    created_by: 'Admin',
  },
  {
    id: 10,
    vendor_name: 'Sparkle Designers Hub',
    vendor_code: 'VEN1032',
    contact_person: 'Sarathy',
    contact_number: '+919755523249',
    material_type: ['Silver'],
    branch: 'Salem',
    created_by: 'Admin',
  },
];
const paymentData = [
  {
    id: 1,
    date: '12/02/2025',
    grn_no: 'GRN 01/24-25',
    total_purchase: '₹1,50,00,000',
    total_paid: '₹1,20,00,000',
    outstanding: '₹30,00,000',
  },
  {
    id: 2,
    date: '15/02/2025',
    grn_no: 'GRN 02/24-25',
    total_purchase: '₹1,50,00,000',
    total_paid: '₹1,20,00,000',
    outstanding: '₹30,00,000',
  },
  {
    id: 3,
    date: '20/02/2025',
    grn_no: 'GRN 03/24-25',
    total_purchase: '₹1,50,00,000',
    total_paid: '₹1,20,00,000',
    outstanding: '₹30,00,000',
  },
  {
    id: 4,
    date: '25/02/2025',
    grn_no: 'GRN 04/24-25',
    total_purchase: '₹1,50,00,000',
    total_paid: '₹1,20,00,000',
    outstanding: '₹30,00,000',
  },
  {
    id: 5,
    date: '03/03/2025',
    grn_no: 'GRN 05/24-25',
    total_purchase: '₹1,50,00,000',
    total_paid: '₹1,20,00,000',
    outstanding: '₹30,00,000',
  },
  {
    id: 6,
    date: '10/03/2025',
    grn_no: 'GRN 06/24-25',
    total_purchase: '₹1,50,00,000',
    total_paid: '₹1,20,00,000',
    outstanding: '₹30,00,000',
  },
  {
    id: 7,
    date: '15/03/2025',
    grn_no: 'GRN 07/24-25',
    total_purchase: '₹1,50,00,000',
    total_paid: '₹1,20,00,000',
    outstanding: '₹30,00,000',
  },
  {
    id: 8,
    date: '20/03/2025',
    grn_no: 'GRN 08/24-25',
    total_purchase: '₹1,50,00,000',
    total_paid: '₹1,20,00,000',
    outstanding: '₹30,00,000',
  },
  {
    id: 9,
    date: '25/03/2025',
    grn_no: 'GRN 09/24-25',
    total_purchase: '₹1,50,00,000',
    total_paid: '₹1,20,00,000',
    outstanding: '₹30,00,000',
  },
  {
    id: 10,
    date: '30/03/2025',
    grn_no: 'GRN 10/24-25',
    total_purchase: '₹1,50,00,000',
    total_paid: '₹1,20,00,000',
    outstanding: '₹30,00,000',
  },
];

const outOfStockData = [
  {
    id: 1,
    sub_category: 'Flower Design Earrings',
    reorder_level: 25,
  },
  {
    id: 2,
    sub_category: 'Bowl',
    reorder_level: 30,
  },
  {
    id: 3,
    sub_category: 'Modern Ring',
    reorder_level: 15,
  },
  {
    id: 4,
    sub_category: 'Diamond Design Necklace',
    reorder_level: 20,
  },
  {
    id: 5,
    sub_category: 'New Bricks Bangles',
    reorder_level: 20,
  },
];
const lowStockData = [
  {
    id: 1,
    sub_category: 'Necklace',
    quantity: 20,
    reorder_level: 25,
  },
  {
    id: 2,
    sub_category: 'Bowl',
    quantity: 25,
    reorder_level: 30,
  },
  {
    id: 3,
    sub_category: 'Earrings',
    quantity: 5,
    reorder_level: 15,
  },
  {
    id: 4,
    sub_category: 'Rings',
    quantity: 10,
    reorder_level: 20,
  },
  {
    id: 5,
    sub_category: 'Bracelets',
    quantity: 12,
    reorder_level: 20,
  },
];
const recentSalesData = [
  {
    id: 1,
    date: '19/05/2025',
    invoice_no: 'INV001',
    product_name: '92.5 Silver Ring, Plain Earrings',
    grs_weight: '12.00 g',
    net_weight: '12.00 g',
    quantity: 2,
    total: '12',
  },
  {
    id: 2,
    date: '19/05/2025',
    invoice_no: 'INV002',
    product_name: 'Silver Coin 10g',
    grs_weight: '10.00 g',
    net_weight: '10.00 g',
    quantity: 4,
    total: '25',
  },
  {
    id: 3,
    date: '19/05/2025',
    invoice_no: 'INV003',
    product_name: 'Anklet - Traditional, Chotis, P...',
    grs_weight: '45.50 g',
    net_weight: '45.50 g',
    quantity: 5,
    total: '20',
  },
  {
    id: 4,
    date: '19/05/2025',
    invoice_no: 'INV004',
    product_name: 'Chain - Box Design',
    grs_weight: '30.00 g',
    net_weight: '30.00 g',
    quantity: 1,
    total: '19',
  },
  {
    id: 5,
    date: '19/05/2025',
    invoice_no: 'INV005',
    product_name: 'Bangle Set',
    grs_weight: '35.00 g',
    net_weight: '35.00 g',
    quantity: 2,
    total: '18',
  },
];
const employeeListData = [
  {
    id: 1,
    s_no: 1,
    employee_name: 'Bessie Cooper',
    employee_no: 'EMP 01/24-25',
    profile_image_url:
      'https://ui-avatars.com/api/?name=Bessie+Cooper&background=random',
    department: 'Sale',
    designation: 'Manager',
    employment_type: 'Full - Time',
    module_access: 'Vouchers +1 Module',
    joined_date: '16/08/2013',
  },
  {
    id: 2,
    s_no: 2,
    employee_name: 'Devon Lane',
    employee_no: 'EMP 02/24-25',
    profile_image_url:
      'https://ui-avatars.com/api/?name=Devon+Lane&background=random',
    department: 'Ma',
    designation: 'Manager',
    employment_type: 'Full Time',
    module_access: 'Vouchers +2 Module',
    joined_date: '16/08/2013',
  },
  {
    id: 3,
    s_no: 3,
    employee_name: 'Albert Flores',
    employee_no: 'EMP 03/24-25',
    profile_image_url:
      'https://ui-avatars.com/api/?name=Albert+Flores&background=random',
    department: 'Sal',
    designation: 'Staff',
    employment_type: 'Full Time',
    module_access: 'NA',
    joined_date: '12/06/2020',
  },
  {
    id: 4,
    s_no: 4,
    employee_name: 'Eleanor Pena',
    employee_no: 'EMP 04/24-25',
    profile_image_url:
      'https://ui-avatars.com/api/?name=Eleanor+Pena&background=random',
    department: 'Sec',
    designation: 'Staff',
    employment_type: 'Full Time',
    module_access: 'NA',
    joined_date: '15/08/2017',
  },
  {
    id: 5,
    s_no: 5,
    employee_name: 'Leslie Alexander',
    employee_no: 'EMP 05/24-25',
    profile_image_url:
      'https://ui-avatars.com/api/?name=Leslie+Alexander&background=random',
    department: 'Billi',
    designation: 'Cashier',
    employment_type: 'Full Time',
    module_access: 'NA',
    joined_date: '15/08/2017',
  },
  {
    id: 6,
    s_no: 6,
    employee_name: 'Jenny Wilson',
    employee_no: 'EMP 06/24-25',
    profile_image_url:
      'https://ui-avatars.com/api/?name=Jenny+Wilson&background=random',
    department: 'Sec',
    designation: 'Security Supervisor',
    employment_type: 'Full Time',
    module_access: 'NA',
    joined_date: '18/09/2016',
  },
  {
    id: 7,
    s_no: 7,
    employee_name: 'Cody Fisher',
    employee_no: 'EMP 07/24-25',
    profile_image_url:
      'https://ui-avatars.com/api/?name=Cody+Fisher&background=random',
    department: 'Ma',
    designation: 'Staff',
    employment_type: 'Full Time',
    module_access: 'NA',
    joined_date: '16/08/2013',
  },
  {
    id: 8,
    s_no: 8,
    employee_name: 'Darlene Robertson',
    employee_no: 'EMP 08/24-25',
    profile_image_url:
      'https://ui-avatars.com/api/?name=Darlene+Robertson&background=random',
    department: 'Sec',
    designation: 'Security Guard',
    employment_type: 'Full Time',
    module_access: 'NA',
    joined_date: '07/05/2016',
  },
  {
    id: 9,
    s_no: 9,
    employee_name: 'Jerome Bell',
    employee_no: 'EMP 09/24-25',
    profile_image_url:
      'https://ui-avatars.com/api/?name=Jerome+Bell&background=random',
    department: 'Ma',
    designation: 'Staff',
    employment_type: 'Full Time',
    module_access: 'NA',
    joined_date: '15/08/2017',
  },
  {
    id: 10,
    s_no: 10,
    employee_name: 'Floyd Miles',
    employee_no: 'EMP 10/24-25',
    profile_image_url:
      'https://ui-avatars.com/api/?name=Floyd+Miles&background=random',
    department: 'HR',
    designation: 'Manager',
    employment_type: 'Full Time',
    module_access: 'HR Management',
    joined_date: '28/10/2012',
  },
];
const customersData = [
  {
    id: 1,
    customer_no: 'CID 01/24-25',
    customer_name: 'Gokul',
    mobile_no: '9876543204',
    total_no_of_orders: 2,
    purchase_amount: ' ₹14,00,000',
  },
  {
    id: 2,
    customer_no: 'CID 02/24-25',
    customer_name: 'Madhy',
    mobile_no: '9876543210',
    total_no_of_orders: 3,
    purchase_amount: '₹12,00,000',
  },
  {
    id: 3,
    customer_no: 'CID 03/24-25',
    customer_name: 'Kalai',
    mobile_no: '9876543203',
    total_no_of_orders: 1,
    purchase_amount: '₹12,00,000',
  },
  {
    id: 4,
    customer_no: 'CID 04/24-25',
    customer_name: 'Sarath',
    mobile_no: '9876543206',
    total_no_of_orders: 5,
    purchase_amount: '₹10,00,000',
  },
  {
    id: 5,
    customer_no: 'CID 05/24-25',
    customer_name: 'Sanjay',
    mobile_no: '9876543202',
    total_no_of_orders: 3,
    purchase_amount: '₹14,00,000',
  },
  {
    id: 6,
    customer_no: 'CID 06/24-25',
    customer_name: 'Kannan',
    mobile_no: '9876543201',
    total_no_of_orders: 4,
    purchase_amount: '₹10,00,000',
  },
  {
    id: 7,
    customer_no: 'CID 07/24-25',
    customer_name: 'Kishore',
    mobile_no: '9876543209',
    total_no_of_orders: 3,
    purchase_amount: '₹7,00,000',
  },
  {
    id: 8,
    customer_no: 'CID 08/24-25',
    customer_name: 'Aravind',
    mobile_no: '9876543208',
    total_no_of_orders: 1,
    purchase_amount: '₹10,00,000',
  },
  {
    id: 9,
    customer_no: 'CID 09/24-25',
    customer_name: 'Kathir',
    mobile_no: '9876543205',
    total_no_of_orders: 3,
    purchase_amount: '₹14,00,000',
  },
  {
    id: 10,
    customer_no: 'CID 10/24-25',
    customer_name: 'Sarathy',
    mobile_no: '9876543207',
    total_no_of_orders: 2,
    purchase_amount: '₹7,20,000',
  },
];
const customerOrdersData = [
  {
    id: 1,
    date: '12/02/2025',
    invoice_no: 'INV 01/24-25',
    product_name: '92.5 Silver Ring',
    quantity: 1,
    total_amount: '₹14,000',
    order_type: 'Online',
  },
  {
    id: 2,
    date: '15/02/2025',
    invoice_no: 'INV 02/24-25',
    product_name: 'Silver Coin 10g',
    quantity: 1,
    total_amount: '₹14,000',
    order_type: 'Offline',
  },
  {
    id: 3,
    date: '20/02/2025',
    invoice_no: 'INV 03/24-25',
    product_name: 'Anklet - Traditional',
    quantity: 1,
    total_amount: '₹14,000',
    order_type: 'Offline',
  },
  {
    id: 4,
    date: '25/02/2025',
    invoice_no: 'INV 04/24-25',
    product_name: 'Chain - Box Design',
    quantity: 1,
    total_amount: '₹14,000',
    order_type: 'Offline',
  },
  {
    id: 5,
    date: '03/03/2025',
    invoice_no: 'INV 05/24-25',
    product_name: 'Bangle Set',
    quantity: 1,
    total_amount: '₹14,000',
    order_type: 'Online',
  },
];
const topSellingData = [
  {
    id: 1,
    category_name: 'Earrings',
    image: '/assets/earrings.png',
    weight: '185 g',
    quantity: 85,
    total_sales: '1,50,00,000',
  },
  {
    id: 2,
    category_name: 'Idols',
    image: '/assets/idols.png',
    weight: '150 g',
    quantity: 85,
    total_sales: '1,50,00,000',
  },
  {
    id: 3,
    category_name: 'Rings',
    image: '/assets/rings.png',
    weight: '182 g',
    quantity: 85,
    total_sales: '1,50,00,000',
  },
  {
    id: 4,
    category_name: 'Necklace',
    image: '/assets/necklace.png',
    weight: '108 g',
    quantity: 85,
    total_sales: '1,50,00,000',
  },
  {
    id: 5,
    category_name: 'Accessories',
    image: '/assets/accessories.png',
    weight: '168 g',
    quantity: 85,
    total_sales: '1,50,00,000',
  },
];
const purchaseData = [
  {
    id: 1,
    category_name: 'Earrings',
    image: '/assets/earrings.png',
    weight: '20 g',
    quantity: 85,
    total_sales: '1,50,00,000',
  },
  {
    id: 2,
    category_name: 'Idols',
    image: '/assets/idols.png',
    weight: '05 g',
    quantity: 85,
    total_sales: '1,50,00,000',
  },
  {
    id: 3,
    category_name: 'Rings',
    image: '/assets/rings.png',
    weight: '10 g',
    quantity: 85,
    total_sales: '1,50,00,000',
  },
  {
    id: 4,
    category_name: 'Necklace',
    image: '/assets/necklace.png',
    weight: '50 g',
    quantity: 85,
    total_sales: '1,50,00,000',
  },
  {
    id: 5,
    category_name: 'Accessories',
    image: '/assets/accessories.png',
    weight: '25 g',
    quantity: 85,
    total_sales: '1,50,00,000',
  },
];
const overallStockData = [
  {
    id: 1,
    branch_name: 'ThangaSelvi Silver',
    category_name: 'Earrings',
    category_image: '/assets/earrings.png',
    sub_category: 'Studs',
    sub_category_image: '/assets/studs.png',
    weight: '20 g',
    quantity: 52,
  },
  {
    id: 2,
    branch_name: 'Velli Maligai',
    category_name: 'Idols',
    category_image: '/assets/idols.png',
    sub_category: 'Single Line',
    sub_category_image: '/assets/single-line.png',
    weight: '05 g',
    quantity: 52,
  },
  {
    id: 3,
    branch_name: 'Sri Velli Alangaram',
    category_name: 'Rings',
    category_image: '/assets/rings.png',
    sub_category: 'Plain Rings',
    sub_category_image: '/assets/plain-rings.png',
    weight: '10 g',
    quantity: 42,
  },
  {
    id: 4,
    branch_name: 'Aathira Silver Mart',
    category_name: 'Necklace',
    category_image: '/assets/necklace.png',
    sub_category: 'Pendant',
    sub_category_image: '/assets/pendant.png',
    weight: '50 g',
    quantity: 14,
  },
  {
    id: 5,
    branch_name: 'Annapoorani Velli Chemmal',
    category_name: 'Bangles',
    category_image: '/assets/bangles.png',
    sub_category: 'Antique bangles',
    sub_category_image: '/assets/antique-bangles.png',
    weight: '25 g',
    quantity: 12,
  },
  {
    id: 6,
    branch_name: 'ShineCraft Silver',
    category_name: 'Accessories',
    category_image: '/assets/accessories.png',
    sub_category: 'Silver Coins',
    sub_category_image: '/assets/silver-coins.png',
    weight: '25 g',
    quantity: 25,
  },
  {
    id: 7,
    branch_name: 'VelvetSilver',
    category_name: 'Necklace',
    category_image: '/assets/necklace.png',
    sub_category: 'Pendant',
    sub_category_image: '/assets/pendant.png',
    weight: '25 g',
    quantity: 52,
  },
  {
    id: 8,
    branch_name: 'MoonMist Jewels',
    category_name: 'Rings',
    category_image: '/assets/rings.png',
    sub_category: 'Plain Rings',
    sub_category_image: '/assets/plain-rings.png',
    weight: '25 g',
    quantity: 47,
  },
  {
    id: 9,
    branch_name: 'PureAura Silver',
    category_name: 'Earrings',
    category_image: '/assets/earrings.png',
    sub_category: 'Studs',
    sub_category_image: '/assets/studs.png',
    weight: '25 g',
    quantity: 25,
  },
  {
    id: 10,
    branch_name: 'JewelPetal Silver',
    category_name: 'Idols',
    category_image: '/assets/idols.png',
    sub_category: 'Single Line',
    sub_category_image: '/assets/single-line.png',
    weight: '25 g',
    quantity: 41,
  },
];
export {
  overallStockData,
  purchaseData,
  topSellingData,
  customerOrdersData,
  customersData,
  employeeListData,
  recentSalesData,
  lowStockData,
  outOfStockData,
  paymentData,
  vendorsData,
  stockUpdateData,
  topEmployeeData,
  topBuyingData,
  branchStatsData,
  branchListData,
  salesReturnData,
  salesInvoiceData,
  branchRows,
  ReceiveQuotationList,
  GoldRates,
  cartData,
  categories,
  jewelryProducts,
  filterOptions,
  CardProductData,
  description,
  productDetails,
  priceBreakupData,
  totalAmount,
  jewelleryCare,
  defaultAddresses,
  userDetails,
  CategoryData,
  order,
  wishlistItems,
  cartItems,
  CountryList,
  StateList,
  DistrictList,
  BranchRows,
  CountryRows,
  StateRows,
  UOMRows,
  MaterialTypeRows,
  TagPrintingRows,
  materialTypeOptions,
  categoryOptions,
  subCategoryOptions,
  grnOptions,
  CategoryRows,
  SubCategoryRows,
  VariantRows,
  OfferData,
  vendorListData,
  GRNData,
  purchaseOrderOptions,
  vendorOptions,
  OrderNameOptions,
  MaterialTypeOptions,
  QuotationListData,
  LedgerGroupRows,
  HRManagementEmployeeRow,
  attendanceData,
  receiptsData,
  GRNViewData,
  sampleOrderData,
  sampleCustomerData,
  PurchaseData,
  PurchaseReturnData,
  VendorNameOptions,
  purchaseReturnOptions,
  employeeList,
  roleData,
  incentive,
  CustomerRows,
  productSpecifications,
  priceBreakup,
  totalAmt,
  dummyIncentivesData,
  PayrollData,
  PurchaseOrderData,
  DivyamGoldSaverData,
  PurchaseReturnsData,
  LeaveListDatas,
  ViewQuotationData,
  HolidaysListData,
  payrollDummyData,
  orderData,
  revenueBranchData,
  revenueData,
  assetManagementData,
  MaintenanceHistory,
  StockList,
  planOptions,
  identityProofOptions,
  nomineeRelationOptions,
  BranchWiseData,
  StockHandList,
  LowstockList,
  OutofstockList,
  stockTransferList,
};
