import { Config } from '@constants/Config';
import { SERVICE_URL } from '@constants';
import { apiOptions } from '@utils/apiOptions';
import { apiRequest } from '@utils/apiRequest';

export const EmpCodeAutoGenerationService = {
  getAutoGeneratedCode: async (params?: any) => {
    const options = await apiOptions({
      url: `${Config.BASE_URL}${SERVICE_URL.EMP_CODE_AUTO_GENERATE}`,

      method: 'post',
      params: params,
    });
    return apiRequest(options);
  },
};
