import {
  ActiveDashBoardIcon,
  ActiveMasterTabIcon,
  ActivePurchaseTabIcon,
  AssetActiveIcon,
  AssetIcon,
  BranchActiveIcon,
  BranchIcon,
  CustomerActive,
  CustomerWhite,
  DashboardIcon,
  HrManagementActiveIcon,
  HrManagementIcon,
  JournalActiveIcon,
  JournalIcon,
  MasterTabIcon,
  OnlineActiveIcon,
  OnlineIcon,
  PurchaseTabIcon,
  ReportsActiveIcon,
  ReportsIcon,
  RevenueIcon,
  SalesActiveIcon,
  SalesIcon,
  SavingActiveIcon,
  SavingSchemeIcon,
  StockActiveIcon,
  StockIcon,
  VendorActiveIcon,
  VendorIcon,
  VoucherActiveIcon,
  VoucherIcon,
} from '@assets/Images';
import { RouterLinkProps } from './util-types';

export const superAdminTabLinks = (): RouterLinkProps[] => {
  return [
    {
      id: 1,
      title: 'Dashboard',
      path: '/admin/dashboard',
      Icon: DashboardIcon,
      IconActive: ActiveDashBoardIcon,
      permissionId: 1,
      isParent: true,
    },
    {
      id: 2,
      title: 'Master',
      Icon: MasterTabIcon,
      IconActive: ActiveMasterTabIcon,
      permissionId: 2,
      isParent: true,
      children: [
        {
          id: 1,
          path: '/admin/master/branch',
          title: 'Branch',
          permissionId: 2,
        },
        {
          id: 2,
          path: '/admin/master/vendorList',
          title: 'Vendor',
          permissionId: 2,
        },
        {
          id: 3,
          path: '/admin/master/employee',
          title: 'Employee',
          permissionId: 2,
        },
        {
          id: 4,
          path: '/admin/master/collections',
          title: 'Collections',
          permissionId: 2,
        },
        {
          id: 5,
          path: '/admin/master/uom',
          title: 'UOM',
          permissionId: 2,
        },
        {
          id: 6,
          path: '/admin/master/products',
          title: 'Products',
          permissionId: 2,
        },
        {
          id: 7,
          path: '/admin/master/accounts',
          title: 'Accounts',
          permissionId: 2,
        },
        {
          id: 8,
          path: '/admin/master/tagPrinting',
          title: 'Tag Printing',
          permissionId: 2,
        },
        {
          id: 9,
          path: '/admin/master/offers',
          title: 'Offers',
          permissionId: 2,
        },
        {
          id: 10,
          path: '/admin/master/schemes',
          title: 'Scheme Master',
          permissionId: 2,
        },
      ],
    },
    {
      id: 3,
      title: 'Customer',
      path: '/admin/customer',
      Icon: CustomerWhite,
      IconActive: CustomerActive,
      permissionId: 3,
      isParent: true,
    },
    {
      id: 4,
      title: 'Online Order',
      path: '/admin/onlineOrder',
      Icon: OnlineIcon,
      IconActive: OnlineActiveIcon,
      permissionId: 4,
      isParent: true,
    },
    {
      id: 5,
      title: 'Saving Scheme',
      path: '/admin/savingScheme',
      Icon: SavingSchemeIcon,
      IconActive: SavingActiveIcon,
      permissionId: 5,
      isParent: true,
    },
    {
      id: 6,
      title: 'Stock Management',
      path: '/admin/stock',
      Icon: StockIcon,
      IconActive: StockActiveIcon,
      permissionId: 6,
      isParent: true,
      children: [
        {
          id: 1,
          path: '/admin/stock',
          title: 'Stock',
          permissionId: 6,
        },
        {
          id: 2,
          path: '/admin/stock/transfer',
          title: 'Stock Transfer',
          permissionId: 6,
        },
      ],
    },
    {
      id: 7,
      title: 'Branch',
      path: '/admin/branch/overview',
      Icon: BranchIcon,
      IconActive: BranchActiveIcon,
      permissionId: 7,
      isParent: true,
    },
    {
      id: 8,
      title: 'Vendor',
      path: '/admin/vendorOverview',
      Icon: VendorIcon,
      IconActive: VendorActiveIcon,
      permissionId: 8,
      isParent: true,
    },

    {
      id: 9,
      title: 'Sales Management',
      path: '/admin/salesManagement',
      Icon: SalesIcon,
      IconActive: SalesActiveIcon,
      permissionId: 9,
      isParent: true,
      children: [
        {
          id: 1,
          title: 'Sales',
          path: '/admin/salesManagement',
          permissionId: 9,
        },
        {
          id: 2,
          title: 'Sales Return',
          path: '/admin/salesManagement/salesReturn',
          permissionId: 9,
        },
      ],
    },
    {
      id: 10,
      title: 'Revenue',
      path: '/admin/revenue',
      Icon: RevenueIcon,
      IconActive: ActivePurchaseTabIcon,

      permissionId: 10,
      isParent: true,
    },
    {
      id: 11,
      title: 'Purchase Management',
      Icon: PurchaseTabIcon,
      IconActive: ActivePurchaseTabIcon,
      permissionId: 11,
      isParent: true,
      children: [
        {
          id: 1,
          path: '/admin/purchases/quotation',
          title: 'Quotation ',
          permissionId: 2,
        },
        {
          id: 2,
          path: '/admin/purchases/purchase',
          title: 'Purchase',
          permissionId: 2,
        },
        {
          id: 3,
          path: '/admin/purchases/grn',
          title: 'GRN',
          permissionId: 2,
        },
        {
          id: 4,
          path: '/admin/purchases/return',
          title: 'Purchase Return',
          permissionId: 2,
        },
      ],
    },
    {
      id: 12,
      title: 'Asset Management',
      path: '/admin/assetManagement',
      Icon: AssetIcon,
      IconActive: AssetActiveIcon,
      permissionId: 12,
      isParent: true,
    },
    {
      id: 13,
      title: 'HR Management',
      Icon: HrManagementIcon,
      IconActive: HrManagementActiveIcon,
      permissionId: 13,
      isParent: true,
      children: [
        {
          id: 1,
          path: '/admin/hr/employee',
          title: 'Employee ',
          permissionId: 5,
        },
        {
          id: 2,
          path: '/admin/hr/attendance',
          title: 'Attendance',
          permissionId: 5,
        },
        {
          id: 3,
          path: '/admin/hr/leaves',
          title: 'Leave',
          permissionId: 5,
        },
        {
          id: 4,
          path: '/admin/hr/holidays',
          title: 'Holidays',
          permissionId: 5,
        },
        {
          id: 5,
          path: '/admin/hr/incentives',
          title: 'Incentives',
          permissionId: 5,
        },
        {
          id: 6,
          path: '/admin/hr/payroll',
          title: 'Payroll',
          permissionId: 5,
        },
      ],
    },
    {
      id: 14,
      title: 'Journal Entry',
      path: '/admin/journalEntry',
      Icon: JournalIcon,
      IconActive: JournalActiveIcon,
      permissionId: 14,
      isParent: true,
    },
    {
      id: 15,
      title: 'Voucher',
      path: '/admin/voucher',
      Icon: VoucherIcon,
      IconActive: VoucherActiveIcon,
      permissionId: 15,
      isParent: true,
      children: [
        {
          id: 1,
          path: '/admin/voucher',
          title: 'Payments',
          permissionId: 15,
        },
        {
          id: 2,
          path: '/admin/voucher/receipt',
          title: 'Receipt',
          permissionId: 15,
        },
      ],
    },
    {
      id: 16,
      title: 'Reports',
      path: '/admin/reports',
      Icon: ReportsIcon,
      IconActive: ReportsActiveIcon,
      permissionId: 16,
      isParent: true,
      children: [
        {
          id: 1,
          path: '/admin/reports/abandonedCheckout',
          title: 'Abandoned Checkout',
          permissionId: 16,
        },
        {
          id: 2,
          path: '/admin/reports/purchaseReport',
          title: 'Purchase Report',
          permissionId: 16,
        },
      ],
    },
  ];
};
